/* ============================================================
   문법아 놀자! - 영문법 개념 정적 데이터 (1/4: 초등 40개)
   - AI 없이 정적 데이터만 사용합니다.
   - C() 헬퍼가 필수 필드를 모두 채워 완전한 객체로 만듭니다.
   ============================================================ */
(function () {
  function C(id, sl, gr, cat, un, ti, de, easy, fun, tip, use, mis1, mis2, exq, exa, qc, qa, rel) {
    return {
      id: id, schoolLevel: sl, gradeLevel: gr, category: cat, unit: un, title: ti, type: 'concept',
      shortDescription: de, easyExplanation: easy, funExplanation: fun,
      memoryTip: tip, useWhen: use, commonMistakes: [mis1, mis2],
      examples: [{ q: exq, a: exa }],
      quickCheck: { question: qc, answer: qa },
      relatedConceptIds: rel || []
    };
  }

  var ELEMENTARY = [
    C('el_be_am','elementary','elementary3','sentence','be동사 첫걸음','I am','나는 ~이다를 말할 때 I am을 써요.','I am Minjun(나는 민준이야)처럼 나를 소개할 때 써요. am은 I의 단짝이에요.','am은 I의 단짝 친구! I가 나오면 am이 따라와요.','I-am 짝꿍! I am 기억하기.','자기소개를 할 때 써요.','I is라고 쓰는 것.','I are라고 쓰는 것.','___ a student. 빈칸에 들어갈 말은?','I am','I의 짝꿍 be동사는?','am',['el_be_is','el_intro_self']),
    C('el_be_is','elementary','elementary3','sentence','be동사 첫걸음','He·She·It is','그·그녀·그것은 ~이다를 말할 때 is를 써요.','He is happy(그는 행복해)처럼 한 사람을 말할 때 is를 써요.','is는 혼자 친구 짝꿍! he·she·it 뒤에 와요.','he·she·it-is 셋은 is와 짝꿍.','친구나 동물을 소개할 때 써요.','He are라고 쓰는 것.','She am이라고 쓰는 것.','She ___ my sister. 빈칸에 들어갈 말은?','is','It 뒤에 오는 be동사는?','is',['el_be_am','el_be_are']),
    C('el_be_are','elementary','elementary3','sentence','be동사 첫걸음','You·We·They are','너·우리·그들은 ~이다를 말할 때 are를 써요.','You are kind(너는 친절해)처럼 둘 이상이거나 you일 때 are를 써요.','are는 여럿이 짝꿍! you·we·they 뒤에 와요.','여럿이면 are! you도 are.','여러 명을 말할 때 써요.','They is라고 쓰는 것.','We am이라고 쓰는 것.','They ___ friends. 빈칸에 들어갈 말은?','are','We 뒤에 오는 be동사는?','are',['el_be_is','el_plural_s']),
    C('el_be_not','elementary','elementary3','sentence','be동사 첫걸음','be동사 부정문','~이 아니다는 be동사 뒤에 not을 붙여 말해요.','I am not tired(피곤하지 않아)처럼 am·is·are 뒤에 not을 붙여요.','not은 아니다 스티커! be동사 뒤에 찰싹 붙어요.','be+not=아니다!','아니라고 말할 때 써요.','I am no tired라고 쓰는 것.','not을 be동사 앞에 붙이는 것.','He is ___ a doctor. 빈칸에 들어갈 말은?','not','is not을 줄이면?','isn’t',['el_be_am','el_be_question']),
    C('el_be_question','elementary','elementary4','sentence','be동사 첫걸음','be동사 의문문','~이니?는 be동사를 맨 앞으로 내어 물어요.','Are you happy?(행복하니?)처럼 are를 앞으로! 대답은 Yes, I am이에요.','be동사 앞으로 점프! 맨 앞에 오면 질문이 돼요.','be 앞으로=질문!','물을 때, 확인할 때 써요.','You are happy?로 어순을 안 바꾸는 것.','대답을 Yes, I are로 하는 것.','___ you ready? 빈칸에 들어갈 말은?','Are','Is she tall? 긍정 대답은?','Yes, she is',['el_be_not','el_wh_what']),
    C('el_intro_self','elementary','elementary3','sentence','be동사 첫걸음','자기소개 문장','I am ~. I am ~ years old.로 나를 소개해요.','I am Sua. I am ten years old.(수아, 열 살)처럼 순서대로 말해요.','자기소개는 2문장 마법! 이름+나이예요.','이름·나이 순서로 말하기.','처음 만난 친구에게 써요.','I ten years old로 am을 빼먹는 것.','My name is를 I name is로 쓰는 것.','I am ___ years old. 열 살이면?','ten','이름을 말할 때 쓰는 문장은?','I am ~',['el_be_am','el_greet']),
    C('el_greet','elementary','elementary3','sentence','be동사 첫걸음','인사와 안부','Hello, Good morning, How are you?로 인사해요.','How are you?(어떻게 지내?)에는 I’m fine, thank you로 답해요.','인사는 영어의 하이파이브! Hello로 시작해요.','How are you-I’m fine 짝꿍.','아침 인사, 안부를 물을 때 써요.','How are you?에 Yes로 답하는 것.','Good night를 낮 인사로 쓰는 것.','How are you? 답으로 맞는 것은?','I’m fine, thank you','아침 인사는?','Good morning',['el_intro_self','el_be_are']),
    C('el_there_is','elementary','elementary4','sentence','be동사 첫걸음','There is·are','~이 있다는 There is(하나)·There are(여럿)로 말해요.','There is a book(책이 있어), There are pens처럼 수에 맞춰 골라요.','There is·are는 있다 마법! 하나is·여럿are예요.','하나is·여럿are!','있는 것을 말할 때 써요.','There are a book으로 쓰는 것.','There is pens로 쓰는 것.','___ a cat in the box. 빈칸은?','There is','여럿이 있을 때는?','There are',['el_be_is','el_plural_s']),
    C('el_verb_like','elementary','elementary3','sentence','일반동사 첫걸음','like: 좋아하다','좋아함을 말할 때 I like apples처럼 써요.','I like soccer(축구 좋아해)처럼 like 뒤에 좋아하는 것을 붙여요.','like는 좋아요 자석! 좋아하는 것을 끌어당겨요.','like 뒤는 좋아하는 것.','좋아하는 것을 말할 때 써요.','I like to soccer처럼 쓰는 것.','3인칭에 likes를 안 붙이는 것.','I ___ music. 빈칸에 들어갈 말은?','like','He likes 뒤에 올 수 있는 것은?','soccer',['el_verb_play','el_verb_s']),
    C('el_verb_play','elementary','elementary3','sentence','일반동사 첫걸음','play·go·eat','놀다·가다·먹다는 play, go, eat로 말해요.','I play soccer, I go home, I eat rice처럼 매일 쓰는 말이에요.','기본 동사는 매일 친구! play·go·eat부터 외워요.','매일 쓰는 3동사 외우기.','하루 일과를 말할 때 써요.','I eated로 과거형을 잘못 쓰는 것.','go를 명사로 아는 것.','I ___ to school. 빈칸에 들어갈 말은?','go','먹다는 영어로?','eat',['el_verb_like','el_past_ed']),
    C('el_verb_have','elementary','elementary4','sentence','일반동사 첫걸음','have: 가지다·먹다','가지고 있다·먹다는 have로 말해요.','I have a pen(펜이 있어), I have breakfast(아침을 먹어)처럼 써요.','have는 두 얼굴! 가지다·먹다예요.','가지고·먹으면 have.','소유와 식사를 말할 때 써요.','3인칭에 have를 그대로 쓰는 것.','have를 be동사처럼 쓰는 것.','She ___ a cat. 빈칸에 들어갈 말은?','has','have 뜻 2가지는?','가지다·먹다',['el_verb_like','el_verb_s']),
    C('el_verb_s','elementary','elementary4','sentence','일반동사 첫걸음','3인칭 단수 -s','he·she·it가 하면 동사에 -s를 붙여요.','He plays soccer(그는 축구를 해)처럼 play에 s가 붙어요.','-s는 3인칭 모자! he·she·it 뒤 동사가 써요.','he·she·it+동사 s!','친구·가족을 말할 때 써요.','He play로 s를 빼먹는 것.','I plays처럼 붙이는 것.','She ___ TV. (watch) 빈칸은?','watches','He go의 바른 말은?','He goes',['el_verb_have','el_does_q']),
    C('el_does_q','elementary','elementary4','sentence','일반동사 첫걸음','Do·Does 의문문','일반동사 질문은 Do·Does를 앞에 써요.','Do you like apples?처럼 do를 앞으로! 3인칭은 Does예요.','Do·Does는 질문 모자! 문장 앞에 써요.','he·she·it 질문은 Does.','좋아하는지 물을 때 써요.','Does you like로 쓰는 것.','Does 뒤 동사에 s를 붙이는 것.','___ she swim? 빈칸에 들어갈 말은?','Does','Do you swim? 긍정 대답은?','Yes, I do',['el_verb_s','el_wh_what']),
    C('el_dont_neg','elementary','elementary4','sentence','일반동사 첫걸음','don’t·doesn’t','~하지 않는다는 don’t·doesn’t로 말해요.','I don’t know(몰라), She doesn’t cry처럼 써요.','don’t는 아니다 방패! 동사 앞에 서요.','3인칭 부정은 doesn’t.','싫다고 말할 때 써요.','She don’t로 쓰는 것.','doesn’t cries로 쓰는 것.','He ___ eat meat. 빈칸에 들어갈 말은?','doesn’t','I don’t의 뜻은?','나는 ~하지 않는다',['el_does_q','el_past_did']),
    C('el_wh_what','elementary','elementary4','sentence','의문사 첫걸음','What: 무엇','무엇을 물을 때 What을 써요.','What is this?(이게 뭐야?)처럼 궁금한 것 앞에 붙여요.','What은 무엇 탐정! 궁금한 것을 찾아요.','무엇=What.','모르는 것을 물을 때 써요.','What is you name처럼 쓰는 것.','What과 Which를 구분 못하는 것.','___ is your name? 빈칸에 들어갈 말은?','What','What color do you like? 뜻은?','무슨 색을 좋아하니',['el_be_question','el_wh_where']),
    C('el_wh_where','elementary','elementary4','sentence','의문사 첫걸음','Where: 어디','어디를 물을 때 Where를 써요.','Where is my bag?(가방 어디 있어?)처럼 장소를 물어요.','Where는 어디 탐정! 장소를 찾아요.','어디=Where.','장소를 물을 때, 길을 찾을 때 써요.','Where is they처럼 쓰는 것.','Where와 When을 헷갈리는 것.','___ do you live? 빈칸에 들어갈 말은?','Where','Where is the station? 뜻은?','역이 어디에 있니',['el_wh_what','el_wh_when']),
    C('el_wh_when','elementary','elementary5','sentence','의문사 첫걸음','When·Who·Why','언제는 When, 누구는 Who, 왜는 Why로 물어요.','When is your birthday?처럼 써요.','의문사는 질문 3형제! When·Who·Why예요.','언제When·누구Who·왜Why.','시간·사람·이유를 물을 때 써요.','Why를 어디로 아는 것.','Who is를 Who are로 쓰는 것.','___ is she crying? 이유를 물으면?','Why','생일을 물을 때는?','When',['el_wh_where','el_wh_how']),
    C('el_wh_how','elementary','elementary5','sentence','의문사 첫걸음','How: 어떻게·얼마','방법·상태·나이를 How로 물어요.','How are you?처럼 써요.','How는 어떻게 요술봉! 방법과 상태를 물어요.','How+형용사로 묻기.','방법·나이를 물을 때 써요.','How old를 How many old로 쓰는 것.','How much와 How many를 구분 못하는 것.','___ old are you? 빈칸에 들어갈 말은?','How','How many apples? 뜻은?','사과가 몇 개니',['el_wh_when','mi_compare_basic']),
    C('el_plural_s','elementary','elementary3','article','명사·관사 첫걸음','복수 -s','하나 이상은 명사에 -s를 붙여요.','one apple, two apples처럼 둘부터 s를 붙여요.','-s는 여럿이 모자! 둘 이상이면 써요.','둘 이상이면 -s!','개수를 말할 때 써요.','two apple로 s를 빼먹는 것.','시간·요일에 s를 붙이는 것.','three ___ (book) 빈칸에 들어갈 말은?','books','one 뒤 명사는?','단수',['el_be_are','el_plural_es']),
    C('el_plural_es','elementary','elementary4','article','명사·관사 첫걸음','복수 -es','s·x·ch·sh로 끝나면 -es를 붙여요.','one box, two boxes처럼 es를 붙여요.','-es는 특별 모자! s·x·ch·sh 뒤에 와요.','쉬익 소리 뒤엔 -es.','낱말 끝이 s·x·ch일 때 써요.','boxs로 쓰는 것.','dish를 dishs로 쓰는 것.','one dish, two ___ 빈칸에 들어갈 말은?','dishes','watch의 복수는?','watches',['el_plural_s','el_plural_irregular']),
    C('el_plural_irregular','elementary','elementary5','article','명사·관사 첫걸음','불규칙 복수','child→children, foot→feet처럼 모양이 바뀌어요.','man→men, tooth→teeth처럼 통째로 바뀌어요.','불규칙 복수는 변신 친구! 모양이 바뀌어요.','child·man·foot 변신 외우기.','사람·몸을 말할 때 써요.','childs로 쓰는 것.','men을 mans로 쓰는 것.','one child, two ___ 빈칸에 들어갈 말은?','children','foot의 복수는?','feet',['el_plural_es','el_article_a']),
    C('el_article_a','elementary','elementary4','article','명사·관사 첫걸음','a·an: 하나','하나는 자음 앞 a, 모음 앞 an을 써요.','a dog, an apple처럼 첫 소리로 골라요.','a·an은 하나 스티커! 소리로 골라요.','모음 소리 앞엔 an!','하나를 셀 때 써요.','an dog로 쓰는 것.','a apple로 쓰는 것.','___ elephant 빈칸에 들어갈 말은?','an','a와 an 기준은?','첫 소리',['el_plural_irregular','el_article_the']),
    C('el_article_the','elementary','elementary5','article','명사·관사 첫걸음','the: 그','정해진 것을 말할 때 the를 써요.','the sun, the book on the desk처럼 정해진 것에 붙어요.','the는 그거 손가락! 정해진 것을 짚어요.','정해졌으면 the!','이미 말한 것을 다시 말할 때 써요.','고유명사 앞에 the를 붙이는 것.','the를 모든 명사에 붙이는 것.','___ moon 빈칸에 들어갈 말은?','the','처음 말하는 하나에는?','a',['el_article_a','el_this_that']),
    C('el_this_that','elementary','elementary3','pos','지시·인칭 첫걸음','this·that·these·those','가까이는 this·these, 멀리는 that·those로 가리켜요.','This is my pen(가까이), That is the moon(멀리)처럼 거리를 봐요.','this·that은 거리 손가락! 가까이·멀리예요.','가까이this·멀리that.','가리키며 말할 때 써요.','these를 단수로 쓰는 것.','that 뒤 복수를 붙이는 것.','___ is a star. 멀리 있으면?','That','가까운 복수는?','these',['el_article_the','el_pron_personal']),
    C('el_pron_personal','elementary','elementary4','pos','지시·인칭 첫걸음','I·he·she·they','사람을 I·you·he·she·it·we·they로 대신해요.','Minjun is tall. He is kind처럼 이름을 대신해요.','대명사는 대타 선수! 이름 대신 출전해요.','이름 반복 말고 대명사!','같은 말을 반복하지 않을 때 써요.','her를 주어로 쓰는 것.','me를 주어로 쓰는 것.','Sua is kind. ___ is my friend. 빈칸은?','She','we의 뜻은?','우리',['el_this_that','el_pron_my']),
    C('el_pron_my','elementary','elementary5','pos','지시·인칭 첫걸음','my·your·mine·yours','나의는 my, 너의 것은 yours처럼 소유를 말해요.','This is my book, That is yours처럼 써요.','my는 내 것 스티커! 뒤에 명사가 와요.','my+명사, mine은 혼자!','내 물건을 말할 때 써요.','my book을 mine book으로 쓰는 것.','your와 yours를 구분 못하는 것.','This is ___ pen. (I) 빈칸은?','my','That pen is ___ (내 것). 빈칸은?','mine',['el_pron_personal','el_wh_whose']),
    C('el_wh_whose','elementary','elementary6','pos','지시·인칭 첫걸음','Whose: 누구의','누구의 것인지 물을 때 Whose를 써요.','Whose bag is this?(누구 가방이야?)처럼 주인을 찾아요.','Whose는 주인 탐정! 주인을 찾아요.','누구의=Whose.','주인을 물을 때 써요.','Whose를 Who’s와 헷갈리는 것.','Whose 뒤 명사를 빼먹는 것.','___ pencil is this? 빈칸에 들어갈 말은?','Whose','Who’s와 Whose는 같을까?','다르다',['el_pron_my','el_article_the']),
    C('el_present_simple','elementary','elementary5','tense','현재·과거 첫걸음','현재: I play','습관·사실은 현재형으로 말해요.','I go to school, The sun rises처럼 써요.','현재형은 매일 일기! 습관과 사실을 말해요.','습관·사실은 현재형.','습관·사실을 말할 때 써요.','어제도 현재형으로 쓰는 것.','3인칭 s를 빼먹는 것.','The sun ___ in the east. 빈칸은?','rises','매일 하는 일은 무슨 시제?','현재',['el_verb_s','el_past_ed']),
    C('el_past_ed','elementary','elementary5','tense','현재·과거 첫걸음','과거 -ed','지난 일은 동사에 -ed를 붙여 말해요.','I played soccer처럼 -ed를 붙여요.','과거형은 어제 도장! -ed를 찍어요.','규칙 과거는 -ed.','지난 일을 말할 때 써요.','어제를 현재형으로 쓰는 것.','watchd처럼 e를 빼먹는 것.','I ___ TV yesterday. (watch) 빈칸은?','watched','play의 과거형은?','played',['el_present_simple','el_past_irregular']),
    C('el_past_irregular','elementary','elementary5','tense','현재·과거 첫걸음','불규칙 과거','go→went, eat→ate처럼 모양이 바뀌어요.','I went home, I ate rice처럼 통째로 외워요.','불규칙 과거는 변신 친구! go·eat·see부터 외워요.','went·ate·seen 순서로 외우기.','지난 일을 말할 때 써요.','goed로 쓰는 것.','eated로 쓰는 것.','I ___ to Jeju. (go, 과거) 빈칸은?','went','eat의 과거형은?','ate',['el_past_ed','el_past_was']),
    C('el_past_was','elementary','elementary5','tense','현재·과거 첫걸음','was·were','과거의 ~이었다는 was·were로 말해요.','I was happy, They were tired처럼 I·he·she·it은 was예요.','was·were는 어제 be동사! I·he는 was예요.','I·he·she·it+was.','어제 상태를 말할 때 써요.','They was로 쓰는 것.','You was로 쓰는 것.','I ___ sick yesterday. 빈칸은?','was','They 뒤 과거 be동사는?','were',['el_past_irregular','el_will']),
    C('el_past_did','elementary','elementary6','tense','현재·과거 첫걸음','Did·didn’t','과거 질문·부정은 Did·didn’t로 해요.','Did you go?처럼 did 뒤 동사는 원형이에요.','Did는 과거 질문 모자! 뒤 동사는 원형이에요.','did 뒤 동사는 원형!','지난 일을 물을 때 써요.','Did you went로 쓰는 것.','didn’t goed로 쓰는 것.','___ you eat lunch? 빈칸은?','Did','I didn’t go의 뜻은?','안 갔어',['el_past_ed','el_dont_neg']),
    C('el_will','elementary','elementary6','tense','현재·과거 첫걸음','will: ~할 것이다','미래는 will+동사원형으로 말해요.','I will help you처럼 will 뒤는 원형이에요.','will은 미래 약속! 뒤는 원형이에요.','will+원형=미래.','약속·예정을 말할 때 써요.','will helps로 쓰는 것.','will을 과거에 쓰는 것.','I ___ swim tomorrow. 빈칸은?','will','내일 비가 올 것 같아는?','It will rain tomorrow',['el_past_was','el_goingto']),
    C('el_goingto','elementary','elementary6','tense','현재·과거 첫걸음','be going to','계획된 미래는 be going to로 말해요.','I am going to travel처럼 확실한 계획에 써요.','be going to는 계획표! 정해진 미래예요.','계획이면 be going to.','주말 계획을 말할 때 써요.','I going to로 be를 빼먹는 것.','will과 뜻이 완전히 같다고 아는 것.','She ___ going to dance. 빈칸은?','is','여행 계획을 말할 때는?','be going to',['el_will','el_progressive']),
    C('el_progressive','elementary','elementary6','tense','현재·과거 첫걸음','be+~ing: 하고 있다','지금 하는 일은 be+~ing로 말해요.','I am playing now처럼 am+playing이에요.','-ing는 지금 진행 중! be와 짝꿍이에요.','be+ing=지금 하고 있음.','지금 하는 일을 말할 때 써요.','I playing으로 be를 빼먹는 것.','I am play로 ing를 빼먹는 것.','Look! He ___ running. 빈칸은?','is','~ing 앞 be동사는?','주어에 맞추기',['el_goingto','el_prep_in']),
    C('el_prep_in','elementary','elementary4','pos','전치사·수식 첫걸음','in·on·under','위치는 in(안에)·on(위에)·under(아래)로 말해요.','in the box, on the desk처럼 써요.','전치사는 위치 사진! in·on·under예요.','안에in·위에on·아래under.','위치를 말할 때 써요.','on the box를 안에로 아는 것.','in을 시간에만 쓰는 말로 아는 것.','The cat is ___ the table. 아래면?','under','책상 위에는?','on',['el_progressive','el_prep_time']),
    C('el_prep_time','elementary','elementary5','pos','전치사·수식 첫걸음','at·on·in: 시간','시간은 at(시각)·on(요일·날짜)·in(월·년)으로 말해요.','at 3, on Monday, in May처럼 단위가 커지면 in이에요.','시간 전치사는 크기 순서! at·on·in예요.','시각at·요일on·월년in.','약속 시간을 말할 때 써요.','on 3 o’clock로 쓰는 것.','in Monday로 쓰는 것.','___ Sunday 빈칸에 들어갈 말은?','on','2026년 앞에는?','in',['el_prep_in','el_adj']),
    C('el_adj','elementary','elementary4','pos','전치사·수식 첫걸음','형용사: big·happy','모습·성질은 big, happy, red로 말해요.','a big house처럼 명사 앞에서 꾸며줘요.','형용사는 꾸밈 리본! 명사 앞에 묶어요.','명사 앞 꾸밈은 형용사.','모습을 말할 때 써요.','형용사를 동사처럼 쓰는 것.','a house big으로 뒤에 쓰는 것.','a ___ flower (red) 빈칸은?','red','기분을 말할 때는?','형용사',['el_prep_time','el_adv']),
    C('el_adv','elementary','elementary5','pos','전치사·수식 첫걸음','부사: -ly','어떻게는 quickly, very, well로 말해요.','run fast처럼 동사를 꾸며줘요.','부사는 도우미 요정! 동사를 꾸며줘요.','어떻게=부사(-ly).','방법·정도를 말할 때 써요.','fast를 fastly로 쓰는 것.','형용사와 부사를 구분 못하는 것.','She sings ___. (beautiful) 빈칸은?','beautifully','very happy에서 very는?','부사',['el_adj','el_can']),
    C('el_can','elementary','elementary4','modal','조동사 첫걸음','can: ~할 수 있다','능력·가능은 can+동사원형으로 말해요.','I can swim처럼 can 뒤는 원형이에요.','can은 할 수 있어 버튼! 뒤는 원형이에요.','can+원형!','잘하는 것을 말할 때 써요.','I can swims로 쓰는 것.','can을 과거에 그대로 쓰는 것.','She ___ dance. 빈칸은?','can','~할 수 없다는?','cannot',['el_adv','mi_modal_basic'])
  ];

  window.GramConceptData = window.GramConceptData || [];
  window.GramConceptData = window.GramConceptData.concat(ELEMENTARY);
})();
