/* ============================================================
   문법아 놀자! - 영문법 개념 정적 데이터 (3/4: 고등 40개)
   - 가정법·준동사·관계사·당위성 심화 + GTELP 연결
   ============================================================ */
(function () {
  function C(id, sl, gr, cat, un, ti, de, easy, fun, tip, use, mis1, mis2, exq, exa, qc, qa, rel) {
    return {
      id: id, schoolLevel: sl, gradeLevel: gr, category: cat, unit: un, title: ti, type: 'concept',
      shortDescription: de, easyExplanation: easy, funExplanation: fun,
      memoryTip: tip, useWhen: use, commonMistakes: [mis1, mis2],
      examples: [{ q: exq, a: exa }],
      quickCheck: { question: qc, answer: qa },
      relatedConceptIds: rel || []
    };
  }

  var HIGH = [
    C('hi_subj_mix','high','high1','subjunctive','가정법 심화','혼합 가정법','if절·주절 시제가 다르면 시간을 따로 맞춰 써요.','If I had left, I would be there처럼 if는 과거완료·주절은 would예요.','혼합 가정법은 시간 따로! if·주절 따로 봐요.','if·주절 시간 따로!','복잡한 상상을 말할 때 써요.','두 절을 같은 시제로 쓰는 것.','would have를 현재에 쓰는 것.','If she had slept, she ___ fine now. 빈칸은?','would be','혼합 가정법 판단 기준은?','두 절 시간 다름',['mi_subj_perf','gt_subj_mix']),
    C('hi_subj_noun','high','high1','subjunctive','가정법 심화','가정법 명사절·형용사절','It is time (that)+과거, as if+과거(완료)로 써요.','It is time we left(이제 떠날 때야)처럼 과거로 말해요.','It is time+과거! as if+과거예요.','time·as if 뒤 과거!','강한 주장·가정을 말할 때 써요.','It is time we leave로 쓰는 것.','as if 뒤 현재형을 쓰는 것.','It is time he ___. (go, 과거) 빈칸은?','went','마치 ~인 것처럼은?','as if',['mi_subj_wish','gt_subj_mix']),
    C('hi_subj_inversion','high','high2','subjunctive','가정법 심화','가정법 도치','If를 빼고 Were·Had·Should를 앞으로 내어 써요.','Were I rich=If I were rich처럼 If 없이 도치해요.','가정법 도치는 If 빼기! Were·Had 앞으로예요.','If 빼고 Were·Had!','격식·시험 문장에서 써요.','Were 뒤 주어를 빼먹는 것.','Had 뒤 p.p.를 빼먹는 것.','___ I rich, I would travel. 빈칸은?','Were','Had+주어+p.p.는?','가정법 과거완료',['hi_subj_mix','gt_subj_mix']),
    C('hi_tense_sequence','high','high1','tense','시제 심화','시제 일치·화법','주절 과거면 종속절도 과거로 맞추고 직접·간접을 바꿔요.','He said he was tired처럼 said 뒤는 was로 맞춰요.','시제 일치는 시간 맞추기! 주절·종속 함께 바꿔요.','주절 과거면 종속도 과거!','말을 전할 때 써요.','said 뒤 현재형을 그대로 쓰는 것.','tomorrow를 그대로 쓰는 것.','He said he ___ busy. (be, 과거) 빈칸은?','was','내일→간접화법은?','the next day',['mi_tense_simple_past','hi_quote_basic']),
    C('hi_reported','high','high1','tense','시제 심화','간접화법 전환','직접 말을 that·if·의문사절로 바꿔 전해요.','“Go!”→told me to go처럼 명령은 to로 바꿔요.','간접화법은 말 옮기기! that·to·if예요.','명령은 to+원형!','말을 전할 때 써요.','시제를 안 바꾸는 것.','asked 뒤 that을 쓰는 것.','“Close it.”→asked me ___ it. 빈칸은?','to close','의문문 간접은?','if·의문사',['hi_tense_sequence','hi_quote_basic']),
    C('hi_quote_basic','high','high1','sentence','시제 심화','직접·간접 인용 기초','직접은 따옴표, 간접은 that·시제 바꾸기로 전해요.','She said, “I am sick.”→She said (that) she was sick처럼 바꿔요.','인용은 따옴표 떼기! that+시제 바꾸기예요.','따옴표 떼고 시제 바꾸기!','말을 전할 때 써요.','that 뒤 현재형을 그대로 쓰는 것.','인칭을 안 바꾸는 것.','She said she ___ ill. (be, 과거) 빈칸은?','was','간접 인용 접속사는?','that',['hi_reported','hi_tense_sequence']),
    C('hi_gerund_inf','high','high1','nonfinite','준동사 심화','동명사·to 의미 차이','remember·forget·stop·try 뒤 to·ing 뜻이 달라요.','remember doing(했던 것 기억) vs to do(할 것 기억)처럼 나눠요.','R-FST 뜻 구별! doing=했던 것, to do=할 것이예요.','R-FST 뜻 차이 외우기!','미묘한 뜻을 말할 때 써요.','뜻 차이 없이 외우는 것.','stop 뒤를 한 가지만 아는 것.','I stopped ___. (smoke, 그만둠) 빈칸은?','smoking','잊었던 것을 기억한다는?','remember ~ing',['mi_gerund_verbs','hi_need_dare']),
    C('hi_need_dare','high','high2','nonfinite','준동사 심화','need·dare·help·let','need·dare 뒤는 to·원형, help·let 뒤는 원형을 써요.','You need to go / You need not go처럼 조동사·본동사로 둘 다 돼요.','need·dare는 두 얼굴! help·let은 원형이에요.','help·let+원형!','도와줌·시킴을 말할 때 써요.','let me to go로 쓰는 것.','help 뒤 to를 무조건 빼는 것.','Let me ___ first. (go) 빈칸은?','go','need not 뒤는?','원형',['hi_gerund_inf','mi_causative']),
    C('hi_part_perf','high','high2','nonfinite','준동사 심화','완료 부정사·분사','먼저 끝남은 to have+p.p.·Having+p.p.로 말해요.','He seems to have left(떠난 것 같아)처럼 have가 먼저 끝남을 알려요.','완료 준동사는 먼저 끝남! to have·Having예요.','먼저 끝났으면 have!','순서를 말할 때 써요.','to leave를 먼저 끝남으로 아는 것.','Having 뒤 원형을 쓰는 것.','___ finished, he went out. 빈칸은?','Having','먼저 온 것 같다는?','seem to have',['hi_gerund_inf','mi_part_conj']),
    C('hi_relative_what','high','high1','relative','관계사 심화','what·that·which 구별','선행사 없으면 what, 사람은 that 불가(소유·최상급은 that)를 나눠 써요.','What you need is rest처럼 what은 선행사를 품어요.','what은 선행사 품기! that은 사람 제한예요.','선행사 없으면 what!','문장을 길게 쓸 때 써요.','사람에 that을 못 쓴다고만 아는 것.','which를 사람에 쓰는 것.','___ you want is here. 빈칸은?','What','최상급 뒤 관계사는?','that',['mi_who_which','hi_relative_prep']),
    C('hi_relative_prep','high','high2','relative','관계사 심화','전치사+관계사·복합관계사','in which=where, of whom처럼 격식으로 쓰고 whoever로 일반화해요.','the house in which I live처럼 전치사+which가 와요.','전치사+관계사는 격식체! in which=where예요.','격식=in which!','격식 글을 쓸 때 써요.','전치사 뒤 that을 쓰는 것.','whoever를 의문사로만 아는 것.','the room ___ I study (in+which) 빈칸은?','in which','누구든지 ~하는 사람은?','whoever',['hi_relative_what','gt_relative_role']),
    C('hi_conn_sub','high','high1','connector','연결어 심화','종속접속사 정밀 구별','when·while·as·since·as soon as를 때·이유로 나눠 써요.','While I slept(자는 동안) vs When I came(왔을 때)처럼 길이를 봐요.','때 연결어는 길이! while=동안, when=순간예요.','동안while·순간when!','때·이유를 말할 때 써요.','while 뒤 순간 동사를 쓰는 것.','since를 since then으로만 아는 것.','___ I was cooking, he came. 빈칸은?','While','~하자마자는?','as soon as',['mi_because','hi_conj_adv']),
    C('hi_conj_adv','high','high1','connector','연결어 심화','접속부사: however 외','therefore·moreover·nevertheless·otherwise를 문장 사이 의미로 나눠 써요.','It rained; therefore, we stayed처럼 ;·. 뒤에 와요.','접속부사는 문장 사이! ; however, 예요.',';·.+접속부사+,!','문단을 이을 때 써요.','접속사처럼 절을 바로 잇는 것.','however 뒤 쉼표를 빼먹는 것.','He was sick; ___, he came. (그러나) 빈칸은?','however','그러므로는?','therefore',['hi_conn_sub','gt_connector_logic']),
    C('hi_mand_adj','high','high2','mandative','당위성 심화','당위 형용사·명사절','important·necessary·essential 뒤 that+(should)+원형으로 써요.','It is vital that he go처럼 go가 원형이에요.','당위 형용사는 INE! important·necessary·essential예요.','INE 뒤 원형!','강한 주장을 말할 때 써요.','he goes로 쓰는 것.','should를 꼭 붙여야 하는 것.','It is essential that she ___. (be) 빈칸은?','be','요구 명사는?','demand·request',['mi_subj_should','gt_mandative']),
    C('hi_modal_idiom','high','high2','modal','조동사 심화','조동사 관용: had better 외','had better·would rather·be supposed to를 나눠 써요.','You had better rest(쉬는 게 좋아)처럼 better 뒤는 원형이에요.','had better+원형! would rather+원형예요.','better·rather 뒤 원형!','충고·선호를 말할 때 써요.','had better to로 쓰는 것.','be supposed to를 추측으로만 아는 것.','You had better ___ now. (leave) 빈칸은?','leave','~하기로 되어 있다는?','be supposed to',['mi_modal_past','gt_modal_ctx']),
    C('hi_passive_adv','high','high2','voice','수동태 심화','수동 진행·완료·조동사','be being+p.p.·have been+p.p.·be+being을 시제에 맞춰 써요.','It is being fixed(고치는 중)처럼 being이 진행을 알려요.','수동 심화는 being·been! 진행being·완료been예요.','진행being·완료been!','상태 변화를 말할 때 써요.','is been fixed로 쓰는 것.','get+p.p.를 못 알아보는 것.','The road ___ repaired. (have, 완료) 빈칸은?','has been','고치는 중이라는?','is being fixed',['mi_passive_by','hi_emphasis']),
    C('hi_emphasis','high','high3','sentence','문장 심화','강조·도치·it~that','It is ~ that, What ~ is로 강조하고 Never 앞으로 도치해요.','It was he that came처럼 강조할 부분을 it·that 사이에 넣어요.','강조는 It~that! 도치는 Never 앞으로예요.','It~that 강조!','강조할 때 써요.','that을 빼먹는 것.','What 뒤 동사를 빼먹는 것.','It was ___ that called. (he) 빈칸은?','he','Never 앞 도치는?','조동사+주어',['hi_passive_adv','gt_mock_grammar']),
    C('hi_ellipsis','high','high3','sentence','문장 심화','생략·대동사·일치','같은 말은 생략·do so·one으로 받고 수를 맞춰요.','I will (go)처럼 뒤를 생략하고 She does too로 받아요.','생략은 같은 말 지우기! do so·one으로 받아요.','같은 말은 생략!','간결하게 말할 때 써요.','생략하면 뜻이 안 통하는 것.','one·it을 구분 못하는 것.','I like tea, and she ___. (do) 빈칸은?','does too','앞 명사 대신 받는 말은?','one',['hi_emphasis','gt_mock_grammar']),
    C('hi_prep_verb','high','high1','pos','전치사·연어 심화','동사+전치사 고정','arrive at·depend on·insist on처럼 짝을 통째로 외워요.','We arrived at noon처럼 at을 붙여요.','전치사 짝꿍 통째로! arrive at·depend on예요.','짝꿍 통째로 외우기!','자연스럽게 말할 때 써요.','arrive to로 쓰는 것.','discuss about으로 쓰는 것.','arrive ___ Seoul 빈칸은?','in','의존한다는?','depend on',['mi_prep_basic','hi_prep_noun']),
    C('hi_prep_noun','high','high2','pos','전치사·연어 심화','형용사·명사+전치사','be fond of·take care of·in charge of를 나눠 써요.','He is fond of music처럼 of가 와요.','형용사+전치사! fond of·good at예요.','fond of·in charge of!','상태·책임을 말할 때 써요.','fond to로 쓰는 것.','charge of를 charge for로 쓰는 것.','in charge ___ sales 빈칸은?','of','~을 돌본다는?','take care of',['hi_prep_verb','gt_vocab_ctx']),
    C('hi_compare_adv','high','high1','comparison','비교 심화','원급·배수·no more','twice as~as, no more than, the+비교급,the+비교급을 나눠 써요.','The more, the better(할수록 더)처럼 the를 붙여요.','the+비교급 쌍둥이! 할수록 ~해요.','The more, the better!','정도·비율을 말할 때 써요.','twice as~than으로 쓰는 것.','no more를 더 이상 없음으로만 아는 것.','___ higher, ___ better. 빈칸은?','The, the','~만큼 2배는?','twice as ~ as',['mi_compare_as','hi_compare_double']),
    C('hi_compare_double','high','high2','comparison','비교 심화','이중비교·비교급 강조','비교급을 more and more·-er and -er로 점점 강조해요.','Better and better(점점 더 좋아)처럼 반복해요.','점점 강조는 반복! -er and -er예요.','반복=점점!','변화를 말할 때 써요.','more better로 쓰는 것.','much를 셀 수 있는 명사에 쓰는 것.','Higher ___ higher. 빈칸은?','and','훨씬 더는?','much·far',['hi_compare_adv','gt_vocab_ctx']),
    C('hi_article_ab','high','high1','article','관사·명사 심화','a·the 추상명사','추상명사는 무관사, 특정·악기는 the를 나눠 써요.','Life is short(인생은 짧아)처럼 일반 추상은 관사 없이 써요.','추상은 관사 없이! 특정·악기는 the예요.','일반 추상=무관사!','추상·악기를 말할 때 써요.','the life is short로 쓰는 것.','play piano로 the를 빼먹는 것.','___ love is blind. 일반이면?','(무관사)','그 사랑(특정)은?','the love',['mi_article_use','hi_noun_count']),
    C('hi_noun_count','high','high1','article','관사·명사 심화','가산·불가산·수량','paper·glass처럼 셀 때·셀 수 없을 때 뜻이 달라요.','a paper(신문 한 부) vs paper(종이)처럼 a 유무로 뜻이 바뀌어요.','가산·불가산 뜻 구별! a paper=신문예요.','a 유무로 뜻 바뀜!','양·종류를 말할 때 써요.','informations로 쓰는 것.','much papers로 쓰는 것.','two ___ of paper 빈칸은?','pieces','조언 하나는?','a piece of advice',['hi_article_ab','hi_quantifier']),
    C('hi_quantifier','high','high2','article','관사·명사 심화','수량·분수·퍼센트','a number of+복수, the number of+단수·복수 수 일치를 나눠 써요.','A number of students are처럼 a number 뒤 복수·복수동사예요.','a number=많은! the number=그 수예요.','a number+복수복수!','수를 말할 때 써요.','The number are로 쓰는 것.','half를 a half로만 아는 것.','A number of birds ___. 빈칸 동사는?','are','3분의 1은?','one third',['hi_noun_count','gt_vocab_ctx']),
    C('hi_pron_each','high','high2','pos','대명사 심화','each·every·either·neither','each·every+단수, either·neither+단수·of+복수를 나눠 써요.','Each student has처럼 each 뒤 단수·단수동사예요.','each·every+단수! either·neither+단수예요.','each·every 단수 받기!','각각·둘 중 하나를 말할 때 써요.','Each students로 쓰는 것.','neither 뒤 복수동사를 쓰는 것.','Each ___ ready. 빈칸은?','is','둘 다 아니라는?','neither',['mi_pron_reflex','hi_concord']),
    C('hi_concord','high','high2','sentence','문장 심화','주어·동사 수 일치','each·one of·not only, 거리·금액 단수를 나눠 맞춰요.','One of the boys is처럼 one of 뒤 복수·단수동사예요.','수 일치는 진짜 주어! one of+단수동사예요.','진짜 주어 찾기!','시험 문장을 고를 때 써요.','The boys is로 쓰는 것.','There 뒤를 앞말에 맞추는 것.','One of them ___ absent. 빈칸은?','is','Ten miles는 단수일까 복수일까?','단수',['hi_pron_each','gt_mock_grammar']),
    C('hi_read_detail','high','high1','connector','독해 연결','세부·추론·어휘 추측','지시어·접속어·앞뒤 문장으로 답을 찾아요.','they·this·however 같은 신호어를 먼저 봐요.','독해는 신호어! they·however를 먼저 봐요.','신호어 먼저 찾기!','긴 글을 읽을 때 써요.','보기부터 읽는 것.','모르는 낱말에 멈추는 것.','they가 가리키는 말은? (앞 문장) 빈칸 답은?','앞 문장의 명사','however 뒤 내용은?','반대·전환',['mi_read_topic','gt_read_main']),
    C('hi_read_struct','high','high2','connector','독해 연결','글 구조·빈칸·순서','주장→근거→예시→정리 흐름으로 빈칸·순서를 맞춰요.','첫 문장 주장, 중간 예시, 끝 정리처럼 구조를 봐요.','글은 주장-근거-정리! 흐름으로 맞춰요.','흐름으로 빈칸·순서!','순서·빈칸 문제를 풀 때 써요.','한 문장만 보고 고르는 것.','접속어를 무시하는 것.','글 첫 문장 역할은?','주장·주제','중간 문장 역할은?','근거·예시',['hi_read_detail','gt_read_main']),
    C('hi_write_cohesion','high','high2','connector','독해 연결','응집·일관성 쓰기','대명사·접속어로 문단을 매끄럽게 이어 써요.','First, Moreover, However로 순서를 알려요.','글쓰기는 연결 신호! First·However예요.','First·Moreover·However!','영작·서술형에서 써요.','연결어 없이 나열하는 것.','같은 접속어만 반복하는 것.','반대 내용을 이을 때는?','However','추가할 때는?','Moreover',['hi_read_struct','gt_read_main']),
    C('hi_listen_signal','high','high1','connector','청취 연결','청취 신호어 듣기','but·however·because·first 뒤 핵심을 듣고 메모해요.','질문 먼저 보고 신호어 뒤를 집중해 들어요.','청취는 신호어 뒤! but·because 뒤예요.','질문 먼저+신호어!','듣기 문제를 풀 때 써요.','처음부터 다 외우려는 것.','숫자·이름을 안 적는 것.','반전 신호어는?','but·however','이유 신호어는?','because',['mi_and_but','gt_listen_mock']),
    C('hi_vocab_root','high','high1','pos','어휘 확장','어근·접사 추론','-dict-·-spect-·-port- 어근으로 뜻을 추측해요.','predict(미리 말하다)=pre+dict처럼 쪼개 봐요.','어근은 뜻 뿌리! dict=말하다예요.','쪼개서 뜻 추측!','모르는 낱말을 만날 때 써요.','어근만 보고 단정하는 것.','접미사 역할을 무시하는 것.','transport의 port 뜻은?','나르다','dict가 들어간 말은?','predict',['mi_vocab_affix','hi_vocab_colloc']),
    C('hi_vocab_colloc','high','high2','pos','어휘 확장','연어·숙어·구동사','take off·look after·run out of를 통째로 외워 써요.','take off(떠오르다/벗다)처럼 뜻이 여러 개예요.','구동사는 통째로! take off·look after예요.','통째로+예문 외우기!','자연스럽게 말할 때 써요.','off만 보고 뜻을 아는 것.','자동사·타동사를 구분 못하는 것.','take ___ (비행기가 뜨다) 빈칸은?','off','돌본다는?','look after',['hi_vocab_root','gt_vocab_ctx']),
    C('hi_confuse_lie','high','high1','subjunctive','헷갈림 정리','lie·lay·lend·borrow','lie-lay-lain(눕다)·lay-laid-laid(놓다)를 나눠 써요.','I lie down(눕는다) vs Lay it down(놓아라)처럼 달라요.','lie·lay 쌍둥이! 눕다lie·놓다lay예요.','눕다lie·놓다lay!','눕기·놓기를 말할 때 써요.','Lay down(I 눕는다)로 쓰는 것.','lend·borrow를 구분 못하는 것.','책을 빌려준다는?','lend','눕다 과거는?','lay',['mi_subj_past','gt_confuse_set']),
    C('hi_confuse_rise','high','high1','subjunctive','헷갈림 정리','rise·raise·sit·seat','rise-rose-risen(오르다)·raise-raised(올리다)를 나눠 써요.','The sun rises vs He raises his hand처럼 자동·타동을 봐요.','rise·raise 형제! 오르다rise·올리다raise예요.','자동rise·타동raise!','오르기·앉기를 말할 때 써요.','raise the sun으로 쓰는 것.','sit·seat을 구분 못하는 것.','손을 든다는?','raise','앉다는?','sit',['hi_confuse_lie','gt_confuse_set']),
    C('hi_confuse_affect','high','high2','subjunctive','헷갈림 정리','affect·effect·중복 피하기','affect(영향 주다)·effect(효과)를 나누고 중복을 피해요.','return back(X)→return처럼 중복을 지워요.','affect는 동사! effect는 명사예요.','A동사·E명사!','격식 글을 쓸 때 써요.','effect를 동사로 쓰는 것.','return back처럼 중복 쓰는 것.','영향을 준다는 동사는?','affect','효과(명사)는?','effect',['hi_confuse_rise','gt_confuse_set']),
    C('hi_error_spot','high','high3','subjunctive','헷갈림 정리','오류 찾기 4점 SET','시제·수 일치·전치사·어법을 4점으로 훑어 골라요.','밑줄 4곳 중 시제·수·짝꿍·어법을 순서대로 봐요.','오류 찾기는 4점 검사! 시제·수·짝꿍·어법예요.','시제→수→짝꿍→어법!','틀린 곳 찾기 문제에서 써요.','한 곳만 보고 고르는 것.','뜻으로만 고르는 것.','오류 찾기 1순위는?','시제','2순위는?','수 일치',['hi_confuse_affect','gt_mock_grammar']),
    C('gt_intro','high','high3','sentence','GTELP 입문','GTELP 문법 지도','26문항 7유형(시제6·가정법6·준동사5·조동사2·연결어2·관계사2·당위성3)을 알아요.','시제·가정법 12문항이 절반! 당위성은 시제로 착각하기 쉬워요.','GTELP는 7유형! 6-6-5-2-2-2-3을 외워요.','6-6-5-2-2-2-3!','실전 전략을 짤 때 써요.','당위성을 시제로 푸는 것.','가정법·시제를 구분 못하는 것.','가장 많은 유형 2개는?','시제·가정법','당위성은 몇 문제?','3문제',['hi_error_spot','gt_tense_mix']),
    C('gt_time_plan','high','high3','tense','GTELP 입문','20분 시간 배분','26문항을 20분에: 1바퀴 15분+검토 5분으로 풀어요.','문항당 45초! 모르면 표시하고 넘어가요.','20분은 15+5! 표시하고 넘어가기예요.','45초+표시 넘기기!','실전 연습할 때 써요.','한 문제에 3분 쓰는 것.','검토 시간을 안 남기는 것.','문항당 목표 시간은?','45초','막히면 어떻게?','표시하고 넘기기',['gt_intro','gt_mock_grammar']),
    C('hi_test_taking','high','high3','sentence','실전 전략','시험 풀이 기술','소거법·신호어·시간 3종으로 실전 점수를 올려요.','확실한 오답 2개를 먼저 지우고 신호어(yesterday·if·because)로 좁혀요.','시험은 소거 게임! 2개 지우면 50%예요.','2개 소거+신호어!','모의고사·실전에서 써요.','첫 느낌만 믿고 검토를 안 하는 것.','모르는 문제에 매달리는 것.','보기 4개 중 2개를 지우면 확률은?','50%','막힌 문제는?','표시하고 넘기기',['hi_ellipsis','gt_mock_grammar'])
  ];

  window.GramConceptData = window.GramConceptData || [];
  window.GramConceptData = window.GramConceptData.concat(HIGH);
})();
