/* ============================================================
   문법아 놀자! - 예문 데이터 150개 (정적 데이터)
   - fields: id, conceptId, en, ko, point(학습 포인트)
   - 개념 상세·오늘의 문법·학습지에 활용됩니다.
   ============================================================ */
(function () {
  function E(id, cid, en, ko, point) {
    return { id: id, conceptId: cid, en: en, ko: ko, point: point || '' };
  }
  window.GramExampleData = [
    E('ex_be_am_1','el_be_am','I am a student.','나는 학생이다.','I+am'),
    E('ex_be_am_2','el_be_am','I am ten years old.','나는 열 살이다.','나이 말하기'),
    E('ex_be_is_1','el_be_is','He is my brother.','그는 내 남동생이다.','he+is'),
    E('ex_be_is_2','el_be_is','She is happy.','그녀는 행복하다.','she+is'),
    E('ex_be_is_3','el_be_is','It is a cat.','그것은 고양이다.','it+is'),
    E('ex_be_are_1','el_be_are','They are friends.','그들은 친구다.','they+are'),
    E('ex_be_are_2','el_be_are','You are kind.','너는 친절하다.','you+are'),
    E('ex_be_are_3','el_be_are','We are ready.','우리는 준비됐다.','we+are'),
    E('ex_be_not_1','el_be_not','I am not tired.','나는 피곤하지 않다.','be+not'),
    E('ex_be_not_2','el_be_not','She isn’t late.','그녀는 늦지 않았다.','isn’t 줄임'),
    E('ex_be_q_1','el_be_question','Are you ready?','준비됐니?','Are 앞 질문'),
    E('ex_be_q_2','el_be_question','Is he tall? Yes, he is.','그는 키가 크니? 응, 그래.','Is 응답'),
    E('ex_intro_1','el_intro_self','My name is Sua.','내 이름은 수아다.','이름 소개'),
    E('ex_greet_1','el_greet','Good morning, class!','안녕, 얘들아! (아침 인사)','아침 인사'),
    E('ex_there_1','el_there_is','There is a book on the desk.','책상 위에 책이 있다.','There is'),
    E('ex_there_2','el_there_is','There are two pens.','펜이 두 자루 있다.','There are'),
    E('ex_like_1','el_verb_like','I like apples.','나는 사과를 좋아한다.','like+명사'),
    E('ex_like_2','el_verb_like','He likes soccer.','그는 축구를 좋아한다.','likes 3인칭'),
    E('ex_play_1','el_verb_play','I play soccer after school.','나는 방과 후에 축구를 한다.','play 습관'),
    E('ex_play_2','el_verb_play','We go home at 4.','우리는 4시에 집에 간다.','go 현재'),
    E('ex_have_1','el_verb_have','I have a pen.','펜이 한 자루 있다.','have 소유'),
    E('ex_have_2','el_verb_have','She has breakfast at 7.','그녀는 7시에 아침을 먹는다.','has+식사'),
    E('ex_s_1','el_verb_s','He watches TV.','그는 TV를 본다.','watch→watches'),
    E('ex_s_2','el_verb_s','She goes to school by bus.','그녀는 버스로 학교에 간다.','go→goes'),
    E('ex_does_1','el_does_q','Does she swim? Yes, she does.','그녀는 수영하니? 응.','Does 질문'),
    E('ex_dont_1','el_dont_neg','He doesn’t eat meat.','그는 고기를 먹지 않는다.','doesn’t'),
    E('ex_what_1','el_wh_what','What is your name?','네 이름이 뭐니?','What 질문'),
    E('ex_where_1','el_wh_where','Where do you live?','어디에 사니?','Where 질문'),
    E('ex_when_1','el_wh_when','When is your birthday?','네 생일은 언제니?','When 질문'),
    E('ex_why_1','el_wh_when','Why are you sad?','왜 슬퍼?','Why 질문'),
    E('ex_how_1','el_wh_how','How old are you?','몇 살이니?','How old'),
    E('ex_howmany_1','el_wh_how','How many apples?','사과가 몇 개니?','How many'),
    E('ex_plu_1','el_plural_s','Two apples, please.','사과 두 개 주세요.','복수 -s'),
    E('ex_plu_2','el_plural_es','Two boxes are here.','상자가 두 개 있다.','복수 -es'),
    E('ex_plu_3','el_plural_irregular','Three children are playing.','아이 셋이 놀고 있다.','children'),
    E('ex_a_1','el_article_a','I see a dog.','개 한 마리가 보인다.','a+자음'),
    E('ex_a_2','el_article_a','She ate an apple.','그녀는 사과 하나를 먹었다.','an+모음'),
    E('ex_the_1','el_article_the','Look at the moon!','달을 봐!','the 유일'),
    E('ex_this_1','el_this_that','This is my pen.','이것은 내 펜이다.','this 가까이'),
    E('ex_that_1','el_this_that','That is the school.','저것은 학교다.','that 멀리'),
    E('ex_pron_1','el_pron_personal','Minjun is tall. He is kind.','민준은 키가 크다. 그는 친절하다.','He 대타'),
    E('ex_my_1','el_pron_my','This is my book.','이것은 내 책이다.','my+명사'),
    E('ex_mine_1','el_pron_my','That pen is mine.','저 펜은 내 것이다.','mine 혼자'),
    E('ex_whose_1','el_wh_whose','Whose bag is this?','이것은 누구 가방이니?','Whose'),
    E('ex_pres_1','el_present_simple','The sun rises in the east.','해는 동쪽에서 뜬다.','사실 현재'),
    E('ex_past_1','el_past_ed','I watched TV yesterday.','어제 TV를 봤다.','-ed 과거'),
    E('ex_past_2','el_past_irregular','We went to Jeju.','우리는 제주에 갔다.','went'),
    E('ex_was_1','el_past_was','I was sick yesterday.','어제 아팠다.','was'),
    E('ex_did_1','el_past_did','Did you go? Yes, I did.','갔니? 응.','Did 질문'),
    E('ex_will_1','el_will','I will help you.','도와줄게.','will 약속'),
    E('ex_going_1','el_goingto','We are going to travel.','여행할 예정이다.','be going to'),
    E('ex_prog_1','el_progressive','Look! He is running.','봐! 그가 달리고 있다.','be+ing'),
    E('ex_prep_1','el_prep_in','The cat is under the table.','고양이가 탁자 아래 있다.','under'),
    E('ex_prept_1','el_prep_time','School starts at 9 on Monday.','학교는 월요일 9시에 시작한다.','at·on'),
    E('ex_adj_1','el_adj','It is a red flower.','빨간 꽃이다.','형용사 꾸밈'),
    E('ex_adv_1','el_adv','She sings beautifully.','그녀는 아름답게 노래한다.','부사 -ly'),
    E('ex_can_1','el_can','I can swim.','수영할 수 있다.','can+원형'),
    E('ex_prog_mi_1','mi_tense_prog','She is studying now.','그녀는 지금 공부 중이다.','현재진행'),
    E('ex_past_mi_1','mi_tense_simple_past','I met him yesterday.','어제 그를 만났다.','과거 met'),
    E('ex_fut_mi_1','mi_tense_future','It is going to rain.','비가 올 예정이다.','be going to'),
    E('ex_perf_1','mi_tense_present_perf','I have finished my work.','일을 끝냈다. (지금 완료)','have+p.p.'),
    E('ex_pperf_1','mi_tense_past_perf','She had left before I came.','내가 오기 전에 떠났다.','had 먼저'),
    E('ex_fperf_1','mi_tense_future_perf','By Friday, I will have done it.','금요일까지 끝낼 것이다.','by+미래완료'),
    E('ex_pprog_1','mi_prog_perf','I have been waiting an hour.','한 시간째 기다리는 중이다.','have been+ing'),
    E('ex_subj_1','mi_subj_past','If I were rich, I would travel.','부자라면 여행할 텐데.','were+would'),
    E('ex_subj_2','mi_subj_perf','If I had studied, I would have passed.','공부했더라면 붙었을 텐데.','had+would have'),
    E('ex_wish_1','mi_subj_wish','I wish I could fly.','날 수 있으면 좋겠다.','wish+과거'),
    E('ex_should_1','mi_subj_should','They insisted he stay.','그가 남아야 한다고 주장했다.','당위 원형'),
    E('ex_ger_1','mi_gerund','Swimming is fun.','수영은 재밌다.','주어 -ing'),
    E('ex_ger_2','mi_gerund_verbs','She enjoys reading.','그녀는 독서를 즐긴다.','enjoy+ing'),
    E('ex_to_1','mi_to_verbs','They decided to leave early.','일찍 떠나기로 했다.','decide+to'),
    E('ex_part_1','mi_participle','a broken window','깨진 창문','p.p. 꾸밈'),
    E('ex_modal_1','mi_modal_basic','You must wear a helmet.','헬멧을 써야 한다.','must 의무'),
    E('ex_modal_2','mi_modal_mean','May I come in?','들어가도 될까요?','May 허락'),
    E('ex_modal_3','mi_modal_past','She must have left.','떠났음이 분명하다.','must have'),
    E('ex_and_1','mi_and_but','I was sick, so I stayed home.','아파서 집에 있었다.','so 결과'),
    E('ex_bec_1','mi_because','If it rains, take an umbrella.','비가 오면 우산을 가져가라.','If 조건'),
    E('ex_although_1','mi_although','Although tired, he kept running.','피곤했지만 계속 달렸다.','Although 양보'),
    E('ex_who_1','mi_who_which','The girl who sings is Sue.','노래하는 소녀는 수다.','who 사람'),
    E('ex_where_1','mi_whose_where','the house where I live','내가 사는 집','where 장소'),
    E('ex_pas_1','mi_passive_be','The cake was eaten.','케이크가 먹혔다.','was+p.p.'),
    E('ex_caus_1','mi_causative','She made me cry.','그녀는 나를 울게 했다.','make+원형'),
    E('ex_comp_1','mi_compare_basic','She is taller than me.','그녀는 나보다 키가 크다.','-er+than'),
    E('ex_super_1','mi_compare_super','He is the best.','그는 최고다.','the best'),
    E('ex_as_1','mi_compare_as','twice as large','두 배만큼 큰','twice as'),
    E('ex_prep_mi_1','mi_prep_basic','She is good at math.','그녀는 수학을 잘한다.','good at'),
    E('ex_tag_1','mi_question_tag','She can swim, can’t she?','그녀는 수영하지, 그렇지?','부의문문'),
    E('ex_never_1','mi_neg_basic','I never smoke.','담배를 절대 안 핀다.','never 단독'),
    E('ex_imp_1','mi_imperative','Wash your hands.','손을 씻어라.','명령 원형'),
    E('ex_either_1','mi_too_either','I don’t like it, either.','나도 싫어.','either 부정'),
    E('ex_art_mi_1','mi_article_use','play the piano','피아노를 치다','악기 the'),
    E('ex_any_1','mi_some_any','Do you have any questions?','질문 있니?','any 질문'),
    E('ex_mix_subj_1','hi_subj_mix','If she had slept, she would be fine.','잤더라면 지금 괜찮을 텐데.','혼합 가정법'),
    E('ex_time_1','hi_subj_noun','It is time we left.','이제 떠날 때다.','time+과거'),
    E('ex_were_1','hi_subj_inversion','Were I rich, I would travel.','부자라면 여행할 텐데.','Were 도치'),
    E('ex_said_1','hi_tense_sequence','He said he was busy.','바쁘다고 말했다.','시제 일치'),
    E('ex_told_1','hi_reported','She told me to go.','가라고 말했다.','told+to'),
    E('ex_rfst_1','hi_gerund_inf','I stopped smoking.','담배를 끊었다.','stop+ing 그만둠'),
    E('ex_need_1','hi_need_dare','Let me go first.','먼저 가게 해줘.','let+원형'),
    E('ex_having_1','hi_part_perf','Having finished, he went out.','끝내고 나서 나갔다.','Having 완료'),
    E('ex_what_2','hi_relative_what','What you want is here.','원하는 것이 여기 있다.','what 품기'),
    E('ex_inwhich_1','hi_relative_prep','the room in which I study','내가 공부하는 방','in which'),
    E('ex_while_1','hi_conn_sub','While I cooked, he came.','요리하는 동안 그가 왔다.','While 동안'),
    E('ex_however_1','hi_conj_adv','He was sick; however, he came.','아팠지만 왔다.','however 반대'),
    E('ex_essential_1','hi_mand_adj','It is essential she be here.','그녀가 여기 있어야 한다.','당위 be'),
    E('ex_better_1','hi_modal_idiom','You had better rest.','쉬는 게 좋겠다.','had better'),
    E('ex_being_1','hi_passive_adv','The road is being fixed.','도로가 고쳐지는 중이다.','being 진행수동'),
    E('ex_it_1','hi_emphasis','It was he that called.','전화한 것은 그였다.','It 강조'),
    E('ex_arrive_1','hi_prep_verb','We arrived in Seoul.','서울에 도착했다.','arrive in'),
    E('ex_fond_1','hi_prep_noun','He is fond of music.','음악을 좋아한다.','fond of'),
    E('ex_the_1','hi_compare_adv','The more, the better.','할수록 더 좋다.','The 쌍둥이'),
    E('ex_love_1','hi_article_ab','Love is blind.','사랑은 눈멀다.','무관사 추상'),
    E('ex_advice_1','hi_noun_count','a piece of advice','조언 하나','piece 단위'),
    E('ex_each_1','hi_pron_each','Each is ready.','각자 준비됐다.','Each 단수'),
    E('ex_oneof_1','hi_concord','One of them is absent.','그 중 하나가 결석이다.','One 단수'),
    E('ex_since_1','gt_tense_mix','She has lived here since 2020.','2020년부터 여기 산다.','since 계속'),
    E('ex_by_1','gt_tense_mix','By Friday, we will have done it.','금요일까지 끝낼 것이다.','by 마감'),
    E('ex_ifwere_1','gt_subj_mix','If I were you, I would rest.','나라면 쉴 텐데.','I were'),
    E('ex_had_1','gt_subj_mix','If he had tried, he would have won.','노력했더라면 이겼을 텐데.','had+would have'),
    E('ex_avoid_1','gt_nonfinite','Avoid being late.','늦지 마라.','avoid+ing'),
    E('ex_mustnot_1','gt_modal_ctx','You must not smoke here.','여기서 담배 금지.','must not'),
    E('ex_but_1','gt_connector_logic','It rained, but we went out.','비가 왔지만 나갔다.','but 역접'),
    E('ex_demand_1','gt_mandative','They demanded he leave.','떠나라고 요구했다.','demand+원형'),
    E('ex_nextday_1','hi_tense_sequence','“tomorrow” → the next day','간접화법 시간 바꾸기','시간 전환'),
    E('ex_gonna_1','mi_listen_basic','gonna (=going to)','구어 줄임 듣기','연음'),
    E('ex_svo_1','mi_write_basic','I like apples because they are sweet.','달콤해서 사과를 좋아한다.','SVO+이유'),
    E('ex_neverinv_1','mi_inversion','Never have I lied.','한 번도 거짓말한 적 없다.','Never 도치'),
    E('ex_return_1','hi_confuse_affect','Please return the book.','책을 반납하세요.','return 중복주의'),
    E('ex_takeoff_1','hi_vocab_colloc','The plane took off.','비행기가 떴다.','take off'),
    E('ex_first_1','hi_write_cohesion','First, wash. Moreover, dry.','먼저 씻고, 게다가 말려라.','연결어 쓰기'),
    E('ex_lookafter_1','hi_vocab_colloc','She looks after her brother.','동생을 돌본다.','look after'),
    E('ex_ina_1','hi_prep_verb','depend on friends','친구에 의존하다','depend on'),
    E('ex_predict_1','hi_vocab_root','predict = pre+dict (미리 말하다)','어근 쪼개기','어근 추론'),
    E('ex_signal_1','hi_listen_signal','but 뒤가 핵심! however 뒤가 반전!','듣기 신호어','신호어 듣기'),
    E('ex_flow_1','hi_read_struct','첫 문장 주장 → 중간 근거 → 끝 정리','글 구조 읽기','구조 독해'),
    E('ex_they_1','hi_read_detail','they = 앞 문장의 명사','지시어 찾기','they 추적'),
    E('ex_timeplan_1','gt_time_plan','26문항 20분 = 문항당 45초','시간 배분','45초 전략'),
    E('ex_dist_1','gt_intro','시제6·가정법6·준동사5·조동사2·연결어2·관계사2·당위성3','7유형 분포','6-6-5-2-2-2-3'),
    E('ex_mock_1','gt_mock_grammar','mock.html에서 20분 타이머로 26문항!','실전 리허설','모의고사'),
    E('ex_listen_q_1','gt_listen_mock','질문 먼저 → 신호어 뒤 집중 → 숫자 메모','청취 3단계','청취 접근'),
    E('ex_ever_1','mi_tense_present_perf','Have you ever eaten sushi?','스시 먹어본 적 있니?','ever 경험'),
    E('ex_lay_1','hi_confuse_lie','Lay it down. (놓아라)','놓다 lay','lay 놓다'),
    E('ex_sat_1','hi_confuse_rise','sit-sat-sat (앉다)','앉다 과거 sat','sit-sat'),
    E('ex_watches_1','el_verb_s','She watches TV every night.','그녀는 매일 밤 TV를 본다.','watches -es'),
    E('ex_doesnt_1','el_dont_neg','He doesn’t cry anymore.','그는 더 이상 울지 않는다.','doesn’t 부정'),
    E('ex_dishes_1','el_plural_es','Two dishes are on the table.','접시가 두 개 탁자 위에 있다.','dishes -es'),
    E('ex_children_1','el_plural_irregular','Many children like candy.','많은 아이들이 사탕을 좋아한다.','children 복수'),
    E('ex_am_1','el_be_am','I am happy today.','나는 오늘 행복하다.','I+am 상태'),
    E('ex_are_q_1','el_be_question','Are they students? Yes, they are.','그들은 학생이니? 응.','Are 응답'),
    E('ex_red_1','el_adj','a big red apple','크고 빨간 사과','형용사 나열')
  ];
})();
