/* ============================================================
   문법아 놀자! - 정적 문제 데이터 (1/4: 초등 80개)
   - P() 헬퍼: id, conceptId, 과정, 학년, 카테고리, 단원, 난이도,
     유형, 질문, 보기(|구분), 정답, 해설, 힌트, 오답이유
   - AI 없이 정적 데이터만 사용. 프론트엔드에서 바로 채점.
   ============================================================ */
(function () {
  function P(id, cid, sl, gl, cat, un, lv, ty, q, ch, a, ex, hi, wr) {
    return { id: id, conceptId: cid, schoolLevel: sl, gradeLevel: gl, category: cat,
      unit: un, level: lv, type: ty, question: q,
      choices: ch ? ch.split('|') : null, answer: a,
      explanation: ex, hint: hi || '', wrongReason: wr || '' };
  }
  var EL = [
    P('p_el_be_am_1','el_be_am','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ a student.”','am|is|are|be','am','I 뒤에는 am이 와요. I am a student.','I-am 짝꿍!','is·are는 I 뒤에 못 와요.'),
    P('p_el_be_am_2','el_be_am','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','바른 문장은?','I am happy.|I is happy.|I are happy.|I be happy.','I am happy.','I의 짝꿍은 am이에요.','I 뒤는?','is·are는 I 짝꿍이 아니에요.'),
    P('p_el_be_is_1','el_be_is','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “He ___ my brother.”','is|am|are|be','is','he·she·it 뒤에는 is가 와요.','he·she·it-is!','am·are는 he 뒤에 못 와요.'),
    P('p_el_be_is_2','el_be_is','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','바른 문장은?','She are tall.|She is tall.|She am tall.|She be tall.','She is tall.','She 뒤에는 is가 와요.','She 뒤는?','are·am은 She 뒤에 못 와요.'),
    P('p_el_be_are_1','el_be_are','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “They ___ friends.”','are|is|am|be','are','you·we·they 뒤에는 are가 와요.','여럿이면 are!','is·am은 they 뒤에 못 와요.'),
    P('p_el_be_are_2','el_be_are','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','바른 문장은?','You is kind.|You are kind.|You am kind.|You be kind.','You are kind.','You 뒤에는 are가 와요.','You도 are!','is·am은 You 뒤에 못 와요.'),
    P('p_el_be_not_1','el_be_not','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “He is ___ a doctor.”','not|no|not is|is no','not','~이 아니다는 be+not이에요.','be+not=아니다!','no는 명사 앞에만 와요.'),
    P('p_el_be_not_2','el_be_not','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','“She is tall.”의 부정문은?','She is not tall.|She not is tall.|She no is tall.|She is no tall.','She is not tall.','not은 be동사 뒤에 와요.','be 뒤 not!','not 위치가 중요해요.'),
    P('p_el_be_q_1','el_be_question','elementary','elementary4','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ you ready?”','Are|Is|Am|Do','Are','you 앞 질문은 Are예요.','be 앞으로=질문!','Do는 일반동사 질문에 써요.'),
    P('p_el_be_q_2','el_be_question','elementary','elementary4','sentence','be동사 첫걸음','easy','multiple_choice','“Is she tall?”에 긍정 대답은?','Yes, she is.|Yes, she are.|Yes, she am.|Yes, she does.','Yes, she is.','질문의 be동사에 맞춰 답해요.','질문 be 그대로!','are·am은 she 짝꿍이 아니에요.'),
    P('p_el_intro_1','el_intro_self','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I am ___ years old.” (열 살)','ten|year|old|age','ten','나이는 숫자로 말해요.','이름·나이 순서!','year·old는 숫자가 아니에요.'),
    P('p_el_intro_2','el_intro_self','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','바른 자기소개는?','I am Sua.|I Sua.|I is Sua.|Am I Sua.','I am Sua.','이름 앞에는 am이 필요해요.','I am ~!','am을 빼먹으면 안 돼요.'),
    P('p_el_greet_1','el_greet','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','“How are you?”에 답으로 맞는 것은?','I’m fine, thank you.|Yes.|Good night.|I am ten.','I’m fine, thank you.','안부에는 상태로 답해요.','How are you-I’m fine!','Yes는 안부 답이 아니에요.'),
    P('p_el_greet_2','el_greet','elementary','elementary3','sentence','be동사 첫걸음','easy','multiple_choice','아침 인사는?','Good morning.|Good night.|Good-bye.|Good job.','Good morning.','아침에는 Good morning이에요.','아침=morning!','Good night는 밤 인사예요.'),
    P('p_el_there_1','el_there_is','elementary','elementary4','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ a cat in the box.”','There is|There are|There am|There be','There is','하나에는 There is예요.','하나is!','are는 여럿에 써요.'),
    P('p_el_there_2','el_there_is','elementary','elementary4','sentence','be동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ two pens.”','There are|There is|There am|There be','There are','여럿에는 There are예요.','여럿are!','is는 하나에 써요.'),
    P('p_el_like_1','el_verb_like','elementary','elementary3','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ music.”','like|likes|liking|to like','like','I·you·we·they 뒤 like는 그대로예요.','I 뒤 그대로!','likes는 he·she·it 뒤에 써요.'),
    P('p_el_like_2','el_verb_like','elementary','elementary3','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “He ___ soccer.”','likes|like|liking|to like','likes','he 뒤 동사에 -s가 붙어요.','he+동사 s!','like 그대로는 he 뒤에 못 와요.'),
    P('p_el_play_1','el_verb_play','elementary','elementary3','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ to school.”','go|goes|went|going','go','I 뒤 go는 그대로예요.','매일 쓰는 동사!','goes는 he·she 뒤에 써요.'),
    P('p_el_play_2','el_verb_play','elementary','elementary3','sentence','일반동사 첫걸음','easy','multiple_choice','“먹다”는 영어로?','eat|ate|eating|eats','eat','먹다는 eat예요.','기본 3동사!','ate는 과거형이에요.'),
    P('p_el_have_1','el_verb_have','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “She ___ a cat.”','has|have|having|haves','has','she 뒤 have는 has가 돼요.','she+has!','have 그대로는 she 뒤에 못 와요.'),
    P('p_el_have_2','el_verb_have','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','“I have breakfast.”의 뜻은?','아침을 먹는다|아침이 있다|아침을 좋아한다|아침에 간다','아침을 먹는다','have+식사는 ~을 먹는다예요.','have+식사=먹다!','가지고 있다는 뜻이 아니에요.'),
    P('p_el_s_1','el_verb_s','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “She ___ TV.” (watch)','watches|watch|watchs|watching','watches','ch 뒤에는 -es가 붙어요.','쉬익 소리 뒤 -es!','watchs는 틀린 철자예요.'),
    P('p_el_s_2','el_verb_s','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','“He go”의 바른 말은?','He goes.|He go.|He going.|He is go.','He goes.','he 뒤 go에 -es가 붙어요.','he+동사 s!','go 그대로는 안 돼요.'),
    P('p_el_does_1','el_does_q','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ she swim?”','Does|Do|Is|Are','Does','she 질문은 Does예요.','she 질문=Does!','Do는 I·you 질문에 써요.'),
    P('p_el_does_2','el_does_q','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','“Do you swim?” 긍정 대답은?','Yes, I do.|Yes, I does.|Yes, I am.|Yes, I does swim.','Yes, I do.','Do 질문에는 do로 답해요.','Do-do 짝꿍!','does는 she·he 답에 써요.'),
    P('p_el_dont_1','el_dont_neg','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “He ___ eat meat.”','doesn’t|don’t|isn’t|not','doesn’t','he 부정은 doesn’t예요.','he 부정=doesn’t!','don’t는 I·you 부정에 써요.'),
    P('p_el_dont_2','el_dont_neg','elementary','elementary4','sentence','일반동사 첫걸음','easy','multiple_choice','“I don’t know.”의 뜻은?','나는 모른다.|나는 안다.|나는 잊었다.|나는 물었다.','나는 모른다.','don’t+동사는 ~하지 않는다예요.','don’t=안 해!','긍정 뜻이 아니에요.'),
    P('p_el_what_1','el_wh_what','elementary','elementary4','sentence','의문사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ is your name?”','What|Where|When|Who','What','이름을 물을 때는 What이에요.','무엇=What!','Where는 장소를 물어요.'),
    P('p_el_what_2','el_wh_what','elementary','elementary4','sentence','의문사 첫걸음','easy','multiple_choice','“What color do you like?”의 뜻은?','무슨 색을 좋아하니|네 이름이 뭐니|어디에 있니|언제 오니','무슨 색을 좋아하니','What color는 무슨 색이에요.','What+명사!','이름을 묻는 말이 아니에요.'),
    P('p_el_where_1','el_wh_where','elementary','elementary4','sentence','의문사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ do you live?”','Where|What|When|Why','Where','사는 곳은 Where로 물어요.','어디=Where!','What은 사물을 물어요.'),
    P('p_el_where_2','el_wh_where','elementary','elementary4','sentence','의문사 첫걸음','easy','multiple_choice','“Where is the station?”의 뜻은?','역이 어디에 있니|역이 언제 여니|역이 뭐니|역이 누구니','역이 어디에 있니','Where is~는 어디에 있니예요.','Where=어디!','시간을 묻는 말이 아니에요.'),
    P('p_el_when_1','el_wh_when','elementary','elementary5','sentence','의문사 첫걸음','easy','multiple_choice','이유를 물을 때 쓰는 말은? “___ is she crying?”','Why|Where|When|What','Why','이유는 Why로 물어요.','왜=Why!','Where는 장소예요.'),
    P('p_el_when_2','el_wh_when','elementary','elementary5','sentence','의문사 첫걸음','easy','multiple_choice','생일을 물을 때는?','When|Why|Who|How','When','때는 When으로 물어요.','언제=When!','Why는 이유예요.'),
    P('p_el_how_1','el_wh_how','elementary','elementary5','sentence','의문사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ old are you?”','How|What|Where|Who','How','나이는 How old로 물어요.','How+형용사!','What old는 틀려요.'),
    P('p_el_how_2','el_wh_how','elementary','elementary5','sentence','의문사 첫걸음','easy','multiple_choice','“How many apples?”의 뜻은?','사과가 몇 개니|사과가 뭐니|사과가 어디 있니|사과가 얼마니','사과가 몇 개니','How many는 몇 개예요.','셀 수 있음many!','장소를 묻는 말이 아니에요.'),
    P('p_el_ps_1','el_plural_s','elementary','elementary3','article','명사·관사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “three ___” (book)','books|book|bookes|bookies','books','셋부터 -s를 붙여요.','둘 이상 -s!','book 그대로는 안 돼요.'),
    P('p_el_ps_2','el_plural_s','elementary','elementary3','article','명사·관사 첫걸음','easy','multiple_choice','바른 문장은?','two apples|two apple|two applees|two applys','two apples.','two 뒤 복수 -s예요.','two+복수!','apple 단수는 안 돼요.'),
    P('p_el_pes_1','el_plural_es','elementary','elementary4','article','명사·관사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “one dish, two ___”','dishes|dishs|dish|dishies','dishes','sh 뒤에는 -es가 붙어요.','쉬익 뒤 -es!','dishs는 틀린 철자예요.'),
    P('p_el_pes_2','el_plural_es','elementary','elementary4','article','명사·관사 첫걸음','easy','multiple_choice','watch의 복수는?','watches|watchs|watch|watchies','watches','ch 뒤에는 -es가 붙어요.','ch 뒤 -es!','watchs는 틀려요.'),
    P('p_el_pirr_1','el_plural_irregular','elementary','elementary5','article','명사·관사 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “one child, two ___”','children|childs|childes|child','children','child 복수는 children이에요.','변신 외우기!','childs는 틀려요.'),
    P('p_el_pirr_2','el_plural_irregular','elementary','elementary5','article','명사·관사 첫걸음','normal','multiple_choice','foot의 복수는?','feet|foots|foot|feets','feet','foot 복수는 feet예요.','foot-feet!','foots는 틀려요.'),
    P('p_el_a_1','el_article_a','elementary','elementary4','article','명사·관사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ elephant”','an|a|the|one','an','모음 소리 앞에는 an이에요.','모음 앞 an!','a는 자음 앞에 써요.'),
    P('p_el_a_2','el_article_a','elementary','elementary4','article','명사·관사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ dog”','a|an|the|one','a','자음 소리 앞에는 a예요.','자음 앞 a!','an은 모음 앞에 써요.'),
    P('p_el_the_1','el_article_the','elementary','elementary5','article','명사·관사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “___ moon”','the|a|an|one','the','유일한 것 앞에는 the예요.','유일=the!','a는 처음 말하는 하나에 써요.'),
    P('p_el_the_2','el_article_the','elementary','elementary5','article','명사·관사 첫걸음','normal','multiple_choice','바른 문장은?','Look at the moon.|Look at a moon.|Look at an moon.|Look at moon.','Look at the moon.','달은 하나뿐이라 the예요.','하나뿐=the!','a moon은 틀려요.'),
    P('p_el_this_1','el_this_that','elementary','elementary3','pos','지시·인칭 첫걸음','easy','multiple_choice','멀리 있는 별을 가리키며? “___ is a star.”','That|This|These|Those','That','멀리 하나는 that이에요.','멀리that!','This는 가까이에 써요.'),
    P('p_el_this_2','el_this_that','elementary','elementary3','pos','지시·인칭 첫걸음','easy','multiple_choice','가까운 복수는? “___ are my shoes.”','These|That|This|Those','These','가까이 여럿은 these예요.','가까이 복수these!','Those는 멀리 여럿이에요.'),
    P('p_el_pron_1','el_pron_personal','elementary','elementary4','pos','지시·인칭 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “Sua is kind. ___ is my friend.”','She|Her|Me|Him','She','주어 자리에는 She가 와요.','주어는 She!','Her는 목적어예요.'),
    P('p_el_pron_2','el_pron_personal','elementary','elementary4','pos','지시·인칭 첫걸음','easy','multiple_choice','we의 뜻은?','우리|너|그들|나','우리','we는 우리예요.','we=우리!','they가 그들이에요.'),
    P('p_el_my_1','el_pron_my','elementary','elementary5','pos','지시·인칭 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “This is ___ pen.” (I)','my|mine|me|I','my','명사 앞 소유는 my예요.','my+명사!','mine은 혼자 써요.'),
    P('p_el_my_2','el_pron_my','elementary','elementary5','pos','지시·인칭 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “That pen is ___.” (내 것)','mine|my|me|I','mine','혼자 쓰는 내 것은 mine이에요.','혼자면 mine!','my 뒤엔 명사가 필요해요.'),
    P('p_el_whose_1','el_wh_whose','elementary','elementary6','pos','지시·인칭 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “___ pencil is this?”','Whose|Who’s|Who|Whom','Whose','누구의는 Whose예요.','누구의=Whose!','Who’s는 Who is의 준말이에요.'),
    P('p_el_whose_2','el_wh_whose','elementary','elementary6','pos','지시·인칭 첫걸음','normal','multiple_choice','Who’s와 Whose는 뜻이 같을까?','다르다|같다|항상 같다|모르겠다','다르다','Who’s=Who is, Whose=누구의예요.','줄임말 주의!','같다고 하면 틀려요.'),
    P('p_el_pres_1','el_present_simple','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “The sun ___ in the east.”','rises|rise|rose|rising','rises','태양(3인칭) 뒤 rise에 -s가 붙어요.','사실은 현재+3인칭 s!','rose는 과거형이에요.'),
    P('p_el_pres_2','el_present_simple','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','매일 하는 일은 무슨 시제로?','현재|과거|미래|진행','현재','습관은 현재형으로 말해요.','습관=현재!','과거는 지난 일에 써요.'),
    P('p_el_ped_1','el_past_ed','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ TV yesterday.” (watch)','watched|watch|watches|watching','watched','yesterday는 과거 신호! -ed를 붙여요.','yesterday+-ed!','watch는 현재형이에요.'),
    P('p_el_ped_2','el_past_ed','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','play의 과거형은?','played|plaied|playd|plays','played','y로 끝나기 전 자음+a? play는 그냥 -ed예요.','규칙 -ed!','plays는 현재 3인칭이에요.'),
    P('p_el_pirr3_1','el_past_irregular','elementary','elementary5','tense','현재·과거 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “I ___ to Jeju.” (go, 과거)','went|goed|go|goes','went','go 과거는 went예요.','went 외우기!','goed는 틀려요.'),
    P('p_el_pirr3_2','el_past_irregular','elementary','elementary5','tense','현재·과거 첫걸음','normal','multiple_choice','eat의 과거형은?','ate|eated|eat|eaten','ate','eat 과거는 ate예요.','eat-ate!','eated는 틀려요.'),
    P('p_el_was_1','el_past_was','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ sick yesterday.”','was|were|am|is','was','I 과거 be동사는 was예요.','I+was!','were는 you·they 과거예요.'),
    P('p_el_was_2','el_past_was','elementary','elementary5','tense','현재·과거 첫걸음','easy','multiple_choice','They 뒤 과거 be동사는?','were|was|are|is','were','they 과거는 were예요.','they+were!','was는 I·he 과거예요.'),
    P('p_el_did_1','el_past_did','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “___ you eat lunch?”','Did|Do|Does|Are','Did','과거 질문은 Did예요.','과거 질문Did!','Do는 현재 질문이에요.'),
    P('p_el_did_2','el_past_did','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','바른 문장은?','Did you go?|Did you went?|Did you goes?|Do you went?','Did you go?.','did 뒤 동사는 원형이에요.','did+원형!','went·goes는 did 뒤에 못 와요.'),
    P('p_el_will_1','el_will','elementary','elementary6','tense','현재·과거 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ swim tomorrow.”','will|would|did|does','will','tomorrow는 미래 신호! will이에요.','tomorrow+will!','did는 과거예요.'),
    P('p_el_will_2','el_will','elementary','elementary6','tense','현재·과거 첫걸음','easy','multiple_choice','바른 문장은?','I will help.|I will helps.|I will helped.|I will helping.','I will help.','will 뒤는 원형이에요.','will+원형!','helps는 will 뒤에 못 와요.'),
    P('p_el_going_1','el_goingto','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “She ___ going to dance.”','is|are|am|be','is','she 앞 be는 is예요.','she+is!','are는 they 앞에 써요.'),
    P('p_el_going_2','el_goingto','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','여행 계획처럼 정해진 미래는?','be going to|will|did|does','be going to','계획된 미래는 be going to예요.','계획=going to!','즉석 결심은 will이에요.'),
    P('p_el_prog_1','el_progressive','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “Look! He ___ running.”','is|are|am|be','is','he 앞 be는 is, running과 짝꿍이에요.','be+ing!','are는 they 앞에 써요.'),
    P('p_el_prog_2','el_progressive','elementary','elementary6','tense','현재·과거 첫걸음','normal','multiple_choice','바른 문장은?','I am playing.|I playing.|I am play.|I playsing.','I am playing.','지금 하는 일은 am+playing이에요.','am+ing!','be를 빼면 안 돼요.'),
    P('p_el_prepin_1','el_prep_in','elementary','elementary4','pos','전치사·수식 첫걸음','easy','multiple_choice','상자 “안에”는? “in the ___”','box|desk|sky|table','box','in the box는 상자 안에예요.','안에in!','on the desk는 책상 위에예요.'),
    P('p_el_prepin_2','el_prep_in','elementary','elementary4','pos','전치사·수식 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “The cat is ___ the table.” (아래)','under|on|in|at','under','아래는 under예요.','아래under!','on은 위에예요.'),
    P('p_el_prept_1','el_prep_time','elementary','elementary5','pos','전치사·수식 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “___ Sunday”','on|in|at|to','on','요일 앞에는 on이에요.','요일on!','in은 월·년 앞에 써요.'),
    P('p_el_prept_2','el_prep_time','elementary','elementary5','pos','전치사·수식 첫걸음','normal','multiple_choice','2026년 앞에는? “___ 2026”','in|on|at|to','in','년 앞에는 in이에요.','월년in!','on은 요일 앞에 써요.'),
    P('p_el_adj_1','el_adj','elementary','elementary4','pos','전치사·수식 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “a ___ flower” (red)','red|run|quickly|eat','red','꽃을 꾸미는 말은 red예요.','명사 앞 형용사!','run은 동사예요.'),
    P('p_el_adj_2','el_adj','elementary','elementary4','pos','전치사·수식 첫걸음','easy','multiple_choice','기분을 말할 때 쓰는 품사는?','형용사|동사|부사|관사','형용사','happy·sad는 형용사예요.','상태=형용사!','동사는 움직임을 말해요.'),
    P('p_el_adv_1','el_adv','elementary','elementary5','pos','전치사·수식 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “She sings ___.” (beautiful)','beautifully|beautiful|beauty|beauties','beautifully','sings를 꾸미는 부사는 beautifully예요.','동사 꾸밈 -ly!','beautiful은 형용사예요.'),
    P('p_el_adv_2','el_adv','elementary','elementary5','pos','전치사·수식 첫걸음','normal','multiple_choice','“very happy”에서 very는?','부사|형용사|동사|명사','부사','happy를 꾸미는 very는 부사예요.','정도=부사!','형용사를 꾸미는 말은 부사예요.'),
    P('p_el_can_1','el_can','elementary','elementary4','modal','조동사 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “She ___ dance.”','can| cans|canning|to can','can','can 뒤는 원형, can은 그대로예요.','can+원형!','cans는 없어요.'),
    P('p_el_can_2','el_can','elementary','elementary4','modal','조동사 첫걸음','easy','multiple_choice','“~할 수 없다”는?','cannot|can not to|no can|can’t to','cannot','cannot는 ~할 수 없다는 뜻이에요.','can’t=cannot!','to를 붙이면 안 돼요.')
  ];
  window.GramProblemData = window.GramProblemData || [];
  window.GramProblemData = window.GramProblemData.concat(EL);
})();
