/* ============================================================
   문법아 놀자! - 정적 문제 데이터 (2/4: 중등 100개)
   - GTELP 7개 유형 기초: 시제·가정법·준동사·조동사·연결어·관계사
   ============================================================ */
(function () {
  function P(id, cid, sl, gl, cat, un, lv, ty, q, ch, a, ex, hi, wr) {
    return { id: id, conceptId: cid, schoolLevel: sl, gradeLevel: gl, category: cat,
      unit: un, level: lv, type: ty, question: q,
      choices: ch ? ch.split('|') : null, answer: a,
      explanation: ex, hint: hi || '', wrongReason: wr || '' };
  }
  var MI = [
    P('p_mi_prog_1','mi_tense_prog','middle','middle1','tense','시제 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “She ___ watching TV now.”','is|are|was|were','is','now는 지금 신호! is+~ing예요.','now=현재진행!','was는 과거예요.'),
    P('p_mi_prog_2','mi_tense_prog','middle','middle1','tense','시제 기본기','normal','multiple_choice','“그때 자고 있었다”는?','was sleeping|is sleeping|sleeps|slept','was sleeping','그때는 과거진행 was+~ing예요.','그때=was+ing!','is sleeping은 지금이에요.'),
    P('p_mi_past_1','mi_tense_simple_past','middle','middle1','tense','시제 기본기','easy','multiple_choice','빈칸에 들어갈 말은? “I ___ him yesterday.” (meet)','met|meet|will meet|meeting','met','yesterday는 과거 신호! meet→met예요.','yesterday=과거!','will meet은 미래예요.'),
    P('p_mi_past_2','mi_tense_simple_past','middle','middle1','tense','시제 기본기','easy','multiple_choice','바른 문장은?','I visited Jeju.|I visit Jeju yesterday.|I will visit Jeju yesterday.|I visiting Jeju.','I visited Jeju.','지난 일은 과거형 visited예요.','지난 일=과거형!','yesterday에 will은 안 돼요.'),
    P('p_mi_fut_1','mi_tense_future','middle','middle1','tense','시제 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “Look at the clouds! It ___ rain.”','is going to|will to|goes to|going','is going to','구름을 보니 비가 올 계획! be going to예요.','확실한 조짐=going to!','will to는 틀려요.'),
    P('p_mi_fut_2','mi_tense_future','middle','middle1','tense','시제 기본기','normal','multiple_choice','지금 결심 “지금 도와줄게”는?','will help|am going to helped|helped|helps','will help','즉석 결심은 will+원형이에요.','즉석=will!','helped는 과거예요.'),
    P('p_mi_perf_1','mi_tense_present_perf','middle','middle2','tense','완료 시제','normal','multiple_choice','빈칸에 들어갈 말은? “I have ___ my homework.” (finish)','finished|finish|finishing|finishs','finished','have 뒤에는 끝난 모양 finished예요.','have+p.p.!','finish 원형은 안 돼요.'),
    P('p_mi_perf_2','mi_tense_present_perf','middle','middle2','tense','완료 시제','normal','multiple_choice','경험을 물을 때는? “Have you ___ sushi?”','ever eaten|eat|ate|eating','ever eaten','경험은 Have+p.p.+ever예요.','경험=ever!','ate는 과거형이에요.'),
    P('p_mi_pperf_1','mi_tense_past_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','빈칸에 들어갈 말은? “She had left ___ I came.”','before|after|whenever|if','before','먼저 떠남은 had left+before예요.','먼저 끝남=had!','after는 나중이에요.'),
    P('p_mi_pperf_2','mi_tense_past_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','had+p.p.는 무슨 시제?','과거완료|현재완료|미래완료|현재진행','과거완료','had+끝난 모양은 과거완료예요.','had=과거완료!','have는 현재완료예요.'),
    P('p_mi_fperf_1','mi_tense_future_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','빈칸에 들어갈 말은? “By 2030, I ___ graduated.”','will have|have|had|am','will have','By+미래는 will have+p.p.예요.','by=미래완료!','have만은 안 돼요.'),
    P('p_mi_fperf_2','mi_tense_future_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','by Friday와 어울리는 시제는?','미래완료|과거|현재진행|현재','미래완료','by+마감은 미래완료 will have예요.','마감=미래완료!','과거는 by ago에 써요.'),
    P('p_mi_pprog_1','mi_prog_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','빈칸에 들어갈 말은? “I have been ___ since morning.” (study)','studying|studied|study|studies','studying','계속+since는 have been+~ing예요.','계속=have been+ing!','studied는 완료예요.'),
    P('p_mi_pprog_2','mi_prog_perf','middle','middle3','tense','완료 시제','hard','multiple_choice','for an hour와 어울리는 시제는?','현재완료진행|과거|미래|현재','현재완료진행','기간 for는 완료진행과 짝꿍이에요.','for+계속!','단순 과거는 기간과 안 어울려요.'),
    P('p_mi_subj1_1','mi_subj_past','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','빈칸에 들어갈 말은? “If I ___ rich, I would travel.” (be)','were|was|am|be','were','가정법 if절 be는 were예요.','I were+would!','was는 가정법에 안 써요.'),
    P('p_mi_subj1_2','mi_subj_past','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','가정법 과거 주절은? “If I knew, I ___ come.”','would|will|can|did','would','가정법 주절은 would+원형이에요.','주절=would!','will은 현실 미래예요.'),
    P('p_mi_subj2_1','mi_subj_perf','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','빈칸에 들어갈 말은? “If I had left, I ___ missed.”','would not have|will not|do not|did not','would not have','과거완료 가정법 주절은 would have+p.p.예요.','would have!','will은 과거 후회에 안 써요.'),
    P('p_mi_subj2_2','mi_subj_perf','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','가정법 과거완료 if절은?','had+p.p.|have+p.p.|would have|will have','had+p.p.','if절은 had+끝난 모양이에요.','if+had!','if절에 would는 안 돼요.'),
    P('p_mi_wish_1','mi_subj_wish','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','빈칸에 들어갈 말은? “I wish I ___ fly.” (can, 과거)','could|can|will|am','could','wish 뒤는 과거! can→could예요.','wish+과거!','can 현재형은 안 돼요.'),
    P('p_mi_wish_2','mi_subj_wish','middle','middle3','subjunctive','가정법 첫걸음','hard','multiple_choice','as if 뒤 시제는? “He acts as if he ___ rich.”','were|is|will be|are','were','as if 뒤도 가정법 과거 were예요.','as if+과거!','is 현재형은 안 돼요.'),
    P('p_mi_should_1','mi_subj_should','middle','middle3','mandative','당위성 첫걸음','hard','multiple_choice','빈칸에 들어갈 말은? “They insisted that he ___.” (stay)','stay|stays|stayed|staying','stay','당위성 that절은 원형 stay예요.','insist+원형!','stays는 틀려요.'),
    P('p_mi_should_2','mi_subj_should','middle','middle3','mandative','당위성 첫걸음','hard','multiple_choice','당위성 동사 3개는?','suggest·insist·demand|like·love·hate|go·come·run|eat·drink·sleep','suggest·insist·demand','요구·제안·명령 동사 뒤 원형이에요.','SID 외우기!','like 뒤는 ~ing·to예요.'),
    P('p_mi_ger_1','mi_gerund','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “___ is good exercise.” (walk)','Walking|Walk|To walking|Walked','Walking','주어 자리 ~하기는 Walking이에요.','주어 -ing!','Walk 원형은 주어가 안 돼요.'),
    P('p_mi_ger_2','mi_gerund','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','바른 문장은?','Swimming is fun.|Swim is fun.|To swimming is fun.|Swimmed is fun.','Swimming is fun.','주어는 동명사 Swimming이에요.','주어=~ing!','Swim 원형은 주어가 안 돼요.'),
    P('p_mi_gv_1','mi_gerund_verbs','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “She finished ___ dinner.” (eat)','eating|to eat|eat|eats','eating','finish 뒤는 ~ing예요.','finish+ing!','to eat은 안 돼요.'),
    P('p_mi_gv_2','mi_gerund_verbs','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','avoid 뒤에 오는 말은?','~ing|to+원형|원형|과거형','~ing','avoid는 동명사만 취해요.','avoid+ing!','to부정사는 안 돼요.'),
    P('p_mi_tv_1','mi_to_verbs','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “They decided ___ early.” (leave)','to leave|leaving|leave|leaves','to leave','decide 뒤는 to+원형이에요.','decide+to!','leaving은 안 돼요.'),
    P('p_mi_tv_2','mi_to_verbs','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','plan 뒤에 오는 말은?','to+원형|~ing|원형|과거형','to+원형','plan은 to부정사를 취해요.','plan+to!','~ing는 안 돼요.'),
    P('p_mi_tor_1','mi_to_roles','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “I came ___ help you.”','to|for|at|in','to','목적 ~하러는 to+원형이에요.','목적=to!','for 뒤는 명사예요.'),
    P('p_mi_tor_2','mi_to_roles','middle','middle2','nonfinite','준동사 기본기','normal','multiple_choice','“time to go”에서 to go는?','형용사|명사|부사|동사','형용사','time을 꾸미니 형용사예요.','명사 꾸밈=형용사!','부사는 동사를 꾸며요.'),
    P('p_mi_part_1','mi_participle','middle','middle3','nonfinite','준동사 기본기','hard','multiple_choice','빈칸에 들어갈 말은? “a ___ door” (close, 닫힌)','closed|closing|close|closes','closed','닫힌(완료)은 p.p. closed예요.','완료=p.p.!','closing은 닫고 있는이에요.'),
    P('p_mi_part_2','mi_participle','middle','middle3','nonfinite','준동사 기본기','hard','multiple_choice','“우는 아기”는?','a crying baby|a cried baby|a cry baby|a cries baby','a crying baby','우는 중(진행)은 crying이에요.','진행=-ing!','cried는 완료예요.'),
    P('p_mi_mb_1','mi_modal_basic','middle','middle1','modal','조동사 기본기','easy','multiple_choice','의무 “헬멧을 써야 해”는? “You ___ wear a helmet.”','must|can|may|might','must','의무는 must예요.','의무=must!','can은 능력이에요.'),
    P('p_mi_mb_2','mi_modal_basic','middle','middle1','modal','조동사 기본기','easy','multiple_choice','충고할 때는? “You ___ rest.”','should|must|can|will','should','충고는 should예요.','충고=should!','must는 강한 의무예요.'),
    P('p_mi_mm_1','mi_modal_mean','middle','middle2','modal','조동사 기본기','normal','multiple_choice','허락 “펜 써도 돼요?”는? “___ I use your pen?”','May|Must|Will|Should','May','허락은 May로 물어요.','허락=May!','Must는 의무예요.'),
    P('p_mi_mm_2','mi_modal_mean','middle','middle2','modal','조동사 기본기','normal','multiple_choice','불확실한 추측은? “It ___ rain.”','might|must|should|will','might','~일지도 몰라 추측은 might예요.','추측=might!','must는 강한 확신이에요.'),
    P('p_mi_mp_1','mi_modal_past','middle','middle3','modal','조동사 기본기','hard','multiple_choice','빈칸에 들어갈 말은? “She ___ forgotten.” (must, 과거)','must have|must has|must having|must had','must have','과거 추측은 must have+p.p.예요.','과거=have!','has는 안 돼요.'),
    P('p_mi_mp_2','mi_modal_past','middle','middle3','modal','조동사 기본기','hard','multiple_choice','“하지 말았어야 했다”는?','should not have|should not|must not|can not have','should not have','과거 후회는 should have예요.','후회=should have!','must not은 현재 금지예요.'),
    P('p_mi_and_1','mi_and_but','middle','middle1','connector','연결어 기본기','easy','multiple_choice','결과 “아파서 집에 있었어”는? “I was sick, ___ I stayed home.”','so|but|or|and','so','결과는 so로 이어요.','결과=so!','but은 반대예요.'),
    P('p_mi_and_2','mi_and_but','middle','middle1','connector','연결어 기본기','easy','multiple_choice','반대를 이을 때는? “tired ___ happy”','but|so|and|or','but','반대는 but으로 이어요.','반대=but!','so는 결과예요.'),
    P('p_mi_bec_1','mi_because','middle','middle1','connector','연결어 기본기','easy','multiple_choice','조건 “비가 오면”은? “___ it rains, take an umbrella.”','If|Because|But|So','If','조건은 If로 말해요.','조건=If!','Because는 이유예요.'),
    P('p_mi_bec_2','mi_because','middle','middle1','connector','연결어 기본기','easy','multiple_choice','이유를 물을 때는?','Why|Where|When|What','Why','이유 질문은 Why예요.','이유=Why!','Where는 장소예요.'),
    P('p_mi_alt_1','mi_although','middle','middle2','connector','연결어 기본기','normal','multiple_choice','양보 “피곤하지만 계속 달렸어”는? “___ tired, he kept running.”','Although|Because|So|And','Although','양보는 Although로 말해요.','양보=Although!','Because는 이유예요.'),
    P('p_mi_alt_2','mi_although','middle','middle2','connector','연결어 기본기','normal','multiple_choice','문장 맨 앞 “그러나”는?','However|But|Because|So','However','문장 시작 그러나는 However예요.','문장 시작=However!','But은 절을 바로 이어요.'),
    P('p_mi_who_1','mi_who_which','middle','middle2','relative','관계사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “The girl ___ sings is Sua.”','who|which|where|when','who','사람 주어는 who예요.','사람who!','which는 사물예요.'),
    P('p_mi_who_2','mi_who_which','middle','middle2','relative','관계사 기본기','normal','multiple_choice','사물을 꾸밀 때는? “the book ___ I read”','which|who|where|when','which','사물은 which예요.','사물which!','who는 사람예요.'),
    P('p_mi_ww_1','mi_whose_where','middle','middle2','relative','관계사 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “the day ___ we met”','when|where|who|which','when','때를 꾸미는 말은 when이에요.','때when!','where는 장소예요.'),
    P('p_mi_ww_2','mi_whose_where','middle','middle2','relative','관계사 기본기','normal','multiple_choice','“내가 사는 집”은? “the house ___ I live”','where|when|who|whose','where','장소를 꾸미는 말은 where예요.','장소where!','when은 때예요.'),
    P('p_mi_pas1_1','mi_passive_be','middle','middle2','voice','수동태 기본기','normal','multiple_choice','빈칸에 들어갈 말은? “The cake ___ eaten.” (be, 과거)','was|is|are|be','was','과거 수동은 was+p.p.예요.','be 시제+p.p.!','is는 현재예요.'),
    P('p_mi_pas1_2','mi_passive_be','middle','middle2','voice','수동태 기본기','normal','multiple_choice','현재 수동태는? “The room ___ cleaned.”','is|was|were|be','is','현재 수동은 is+p.p.예요.','현재=is!','was는 과거예요.'),
    P('p_mi_pas2_1','mi_passive_by','middle','middle3','voice','수동태 기본기','hard','multiple_choice','빈칸에 들어갈 말은? “He was made ___ early.”','to go|go|going|went','to go','make 수동은 to+원형이에요.','수동 make=to!','go 원형은 능동이에요.'),
    P('p_mi_pas2_2','mi_passive_by','middle','middle3','voice','수동태 기본기','hard','multiple_choice','행위자 “공에 맞았다”는? “hit ___ a ball”','by|with|to|for','by','행위자는 by로 말해요.','행위자=by!','with는 도구예요.'),
    P('p_mi_caus_1','mi_causative','middle','middle3','voice','수동태 기본기','hard','multiple_choice','빈칸에 들어갈 말은? “I saw him ___.” (run)','run|to run|running|runs','run','see 뒤는 원형 run이에요.','see+원형!','to run은 안 돼요.'),
    P('p_mi_caus_2','mi_causative','middle','middle3','voice','수동태 기본기','hard','multiple_choice','“나를 울게 했다”는? “made me ___”','cry|to cry|crying|cries','cry','make 뒤는 원형 cry예요.','make+원형!','to cry는 안 돼요.'),
    P('p_mi_comp1_1','mi_compare_basic','middle','middle1','comparison','비교 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “She is ___ than me.” (tall)','taller|tallest|more tall|most tall','taller','짧은 말 비교는 -er+than예요.','짧-er+than!','tallest는 최상급이에요.'),
    P('p_mi_comp1_2','mi_compare_basic','middle','middle1','comparison','비교 첫걸음','easy','multiple_choice','바른 문장은?','more beautiful|beautifuller|more beauty|beautifuler','more beautiful.','긴 말 비교는 more예요.','길more!','beautifuller는 없어요.'),
    P('p_mi_comp2_1','mi_compare_super','middle','middle1','comparison','비교 첫걸음','easy','multiple_choice','빈칸에 들어갈 말은? “He is ___ student.” (good)','the best|better|good|best','the best','good 최상급은 the best예요.','good-best!','better는 비교급이에요.'),
    P('p_mi_comp2_2','mi_compare_super','middle','middle1','comparison','비교 첫걸음','easy','multiple_choice','바른 문장은?','the tallest|tallest|a tallest|tallerest','the tallest.','최상급 앞에는 the예요.','the+-est!','the를 빼면 안 돼요.'),
    P('p_mi_comp3_1','mi_compare_as','middle','middle2','comparison','비교 첫걸음','normal','multiple_choice','빈칸에 들어갈 말은? “twice ___ large”','as|than|more|most','as','배수 비교는 twice as~as예요.','twice as!','than은 비교급에 써요.'),
    P('p_mi_comp3_2','mi_compare_as','middle','middle2','comparison','비교 첫걸음','normal','multiple_choice','“~만큼 ~하지 않다”는?','not as ~ as|not than|not more|not most','not as ~ as','부정 같음은 not as~as예요.','not as!','than은 비교급이에요.'),
    P('p_mi_cnt_1','mi_count_basic','middle','middle2','comparison','비교 첫걸음','normal','multiple_choice','셀 수 없으면? “How ___ rice?”','much|many|few|several','much','셀 수 없는 rice는 much예요.','없음much!','many는 셀 수 있음에 써요.'),
    P('p_mi_cnt_2','mi_count_basic','middle','middle2','comparison','비교 첫걸음','normal','multiple_choice','“조금 있음(긍정)”은?','a few|few|little|none','a few','a few는 조금 있음(긍정)예요.','a 있음=긍정!','few는 거의 없음이에요.'),
    P('p_mi_prep_1','mi_prep_basic','middle','middle1','pos','전치사 기본기','easy','multiple_choice','빈칸에 들어갈 말은? “She is good ___ math.”','at|in|on|to','at','good at은 ~을 잘함이에요.','good at!','in은 관심에 써요.'),
    P('p_mi_prep_2','mi_prep_basic','middle','middle1','pos','전치사 기본기','easy','multiple_choice','“음악에 관심 있음”은?','interested in|interested at|interested on|interested to','interested in','관심은 interested in이에요.','interest in!','at은 잘함에 써요.'),
    P('p_mi_5form_1','mi_conj_basic','middle','middle2','sentence','문장 확장','normal','multiple_choice','빈칸에 들어갈 말은? “I ___ a teacher.” (be)','am|like|eat|run','am','주어+be+보어는 2형식 am예요.','2형식=be!','like는 3형식이에요.'),
    P('p_mi_5form_2','mi_conj_basic','middle','middle2','sentence','문장 확장','normal','multiple_choice','“I like apples.” 문형은?','3형식|1형식|2형식|4형식','3형식','주어+동사+목적어 3형식이에요.','SVO=3형식!','be+보어는 2형식이에요.'),
    P('p_mi_tag_1','mi_question_tag','middle','middle3','sentence','문장 확장','hard','multiple_choice','빈칸에 들어갈 말은? “She can swim, ___ she?”','can’t|can|doesn’t|isn’t','can’t','앞 긍정→뒤 부정 can’t예요.','앞뒤 반대!','can 긍정은 안 돼요.'),
    P('p_mi_tag_2','mi_question_tag','middle','middle3','sentence','문장 확장','hard','multiple_choice','빈칸에 들어갈 말은? “You went, ___ you?”','didn’t|don’t|aren’t|weren’t','didn’t','과거 앞문장은 didn’t로 되물어요.','과거=didn’t!','don’t는 현재예요.'),
    P('p_mi_neg_1','mi_neg_basic','middle','middle1','sentence','문장 확장','normal','multiple_choice','바른 문장은?','I never smoke.|I don’t never smoke.|I never don’t smoke.|I never to smoke.','I never smoke.','never 하나면 not이 필요 없어요.','부정 하나!','don’t never 이중부정은 안 돼요.'),
    P('p_mi_neg_2','mi_neg_basic','middle','middle1','sentence','문장 확장','normal','multiple_choice','“아무도 없다”는?','no one|anyone|someone|everyone','no one','부정 주어는 no one예요.','no=부정!','anyone은 질문·조건에 써요.'),
    P('p_mi_imp_1','mi_imperative','middle','middle1','sentence','문장 확장','easy','multiple_choice','명령 “손 씻어”는? “___ your hands.” (wash)','Wash|Washes|Washed|Washing','Wash','명령은 원형 Wash예요.','명령=원형!','Washes는 3인칭이에요.'),
    P('p_mi_imp_2','mi_imperative','middle','middle1','sentence','문장 확장','easy','multiple_choice','“앉지 마”는?','Don’t sit.|Don’t sits.|No sit.|Not sit.','Don’t sit.','부정 명령은 Don’t+원형이에요.','Don’t+원형!','sits는 안 돼요.'),
    P('p_mi_too_1','mi_too_either','middle','middle2','sentence','문장 확장','normal','multiple_choice','부정 동의 “나도 싫어”는? “I don’t like it, ___.”','either|too|also|so','either','부정 동의는 either예요.','부정either!','too는 긍정 동의예요.'),
    P('p_mi_too_2','mi_too_either','middle','middle2','sentence','문장 확장','normal','multiple_choice','긍정 동의 “나도 그래”는?','so do I|either do I|neither do I|too do I not','so do I','긍정 동의는 so do I예요.','긍정so!','either는 부정이에요.'),
    P('p_mi_art_1','mi_article_use','middle','middle2','article','관사·명사 심화','normal','multiple_choice','빈칸에 들어갈 말은? “play ___ guitar”','the|a|an|one','the','악기 앞에는 the예요.','악기the!','운동 앞은 무관사예요.'),
    P('p_mi_art_2','mi_article_use','middle','middle2','article','관사·명사 심화','normal','multiple_choice','바른 문장은?','have breakfast|have a breakfast|have the breakfast|have breakfasts','have breakfast.','식사 앞은 관사 없이 써요.','식사×!','a breakfast는 틀려요.'),
    P('p_mi_some_1','mi_some_any','middle','middle2','article','관사·명사 심화','normal','multiple_choice','빈칸에 들어갈 말은? “Do you have ___ questions?”','any|some|no|every','any','질문·부정은 any예요.','질문any!','긍정문은 some이에요.'),
    P('p_mi_some_2','mi_some_any','middle','middle2','article','관사·명사 심화','normal','multiple_choice','긍정문 some 예문은?','I have some.|I don’t have some.|Do you have some?|I have any.','I have some.','긍정문은 some을 써요.','긍정some!','부정문은 any예요.'),
    P('p_mi_refl_1','mi_pron_reflex','middle','middle2','pos','대명사 심화','normal','multiple_choice','빈칸에 들어갈 말은? “She taught ___ English.” (스스로)','herself|her|she|hers','herself','스스로는 herself예요.','self 거울!','her는 목적어예요.'),
    P('p_mi_refl_2','mi_pron_reflex','middle','middle2','pos','대명사 심화','normal','multiple_choice','“서로”는?','each other|each self|other each|self each','each other','서로는 each other예요.','서로=each other!','each self는 없어요.'),
    P('p_mi_mind_1','mi_possessive_ing','middle','middle3','pos','대명사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “Do ___ my asking?” (mind)','you mind|you to mind|your mind|you minding','you mind','mind는 Do you mind~?로 물어요.','mind 질문!','minding은 안 돼요.'),
    P('p_mi_mind_2','mi_possessive_ing','middle','middle3','pos','대명사 심화','hard','multiple_choice','바른 문장은?','mind my smoking|mind me smoking|mind I smoking|mind my smoke','mind my smoking.','mind 뒤 소유격+~ing예요.','mind+my+ing!','me smoking은 구어체예요.'),
    P('p_mi_omit_1','mi_relative_omit','middle','middle3','relative','관계사 심화','hard','multiple_choice','생략 가능? “the movie ___ I saw”','(which)|who|whose|where','(which)','목적격 which는 생략돼요.','목적격 생략!','who는 사람 주어예요.'),
    P('p_mi_omit_2','mi_relative_omit','middle','middle3','relative','관계사 심화','hard','multiple_choice','“~하는 것”을 품는 말은? “___ is needed is rest.”','What|Which|Who|Where','What','선행사 품기는 what이에요.','what 품기!','Which는 선행사가 필요해요.'),
    P('p_mi_partc_1','mi_part_conj','middle','middle3','nonfinite','준동사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “___ tired, he slept early.” (be)','Being|Be|Is|Are','Being','~해서 분사구문은 Being이에요.','분사구문!','Be 원형은 안 돼요.'),
    P('p_mi_partc_2','mi_part_conj','middle','middle3','nonfinite','준동사 심화','hard','multiple_choice','먼저 끝남 분사구문은? “___ home, she slept.”','Having arrived|Arrive|Arriving to|Arrived','Having arrived.','먼저 끝남은 Having+p.p.예요.','Having+완료!','Arrived만은 안 돼요.'),
    P('p_mi_inv_1','mi_inversion','middle','middle3','sentence','문장 확장','hard','multiple_choice','도치 “한 번도 거짓말한 적 없어”는? “___ have I lied.”','Never|Always|Often|Ever','Never','부정어 맨 앞은 도치! Never have예요.','부정 앞=도치!','Always는 도치가 안 돼요.'),
    P('p_mi_inv_2','mi_inversion','middle','middle3','sentence','문장 확장','hard','multiple_choice','Not only 뒤 짝꿍은? “Not only ___, but also ...”','he came|he comes|came he|comes he','he came','Not only 뒤는 정상 어순이에요.','뒤는 정상!','도치는 앞절만 해요.'),
    P('p_mi_conc_1','mi_concise','middle','middle3','sentence','문장 확장','hard','multiple_choice','빈칸에 들어갈 말은? “Each of us ___ ready.”','is|are|were|be','is','Each는 단수! is예요.','each+단수!','are는 복수예요.'),
    P('p_mi_conc_2','mi_concise','middle','middle3','sentence','문장 확장','hard','multiple_choice','바른 문장은?','return|return back|repeat again|revert back','return.','return back은 중복! return만 써요.','중복 빼기!','back·again 중복은 안 돼요.'),
    P('p_mi_affix_1','mi_vocab_affix','middle','middle2','pos','어휘 확장','normal','multiple_choice','happy의 반대말은?','unhappy|dishappy|inhappy|nonhappy','unhappy','happy 반대는 unhappy예요.','un=반대!','dishappy는 없어요.'),
    P('p_mi_affix_2','mi_vocab_affix','middle','middle2','pos','어휘 확장','normal','multiple_choice','“다시 ~하다” 접두사는?','re-|un-|dis-|in-','re-','re-는 다시예요.','re=다시!','un-은 반대예요.'),
    P('p_mi_coll_1','mi_collocation','middle','middle3','pos','어휘 확장','normal','multiple_choice','빈칸에 들어갈 말은? “depend ___ him”','on|to|for|at','on','depend on은 ~에 의존하다예요.','depend on!','to는 안 돼요.'),
    P('p_mi_coll_2','mi_collocation','middle','middle3','pos','어휘 확장','normal','multiple_choice','take care of 뜻은?','돌보다|버리다|잃다|팔다','돌보다','take care of는 돌보다예요.','통째로 외우기!','버리다는 throw예요.'),
    P('p_mi_read_1','mi_read_topic','middle','middle3','connector','독해 연결','normal','multiple_choice','주제를 찾을 때 먼저 볼 곳은?','첫·마지막 문장|가운데 예시|보기|각주','첫·마지막 문장','주제는 첫·끝에 있어요.','첫·끝!','보기부터 읽으면 안 돼요.'),
    P('p_mi_read_2','mi_read_topic','middle','middle3','connector','독해 연결','normal','multiple_choice','반복되는 말은 글에서?','핵심어|예시|농담|인용','핵심어','반복=핵심어예요.','반복 찾기!','농담은 주제가 아니에요.'),
    P('p_mi_lis_1','mi_listen_basic','middle','middle2','connector','청취 연결','normal','multiple_choice','들을 때 꼭 적어야 할 것은?','이름·숫자|모든 단어|농담|노래','이름·숫자','이름·숫자는 메모해요.','메모=이름·숫자!','전부를 적을 순 없어요.'),
    P('p_mi_lis_2','mi_listen_basic','middle','middle2','connector','청취 연결','normal','multiple_choice','붙어 들리는 말 예는? “___ (=going to)”','gonna|wanna go to|gotta be|hafta','gonna','going to는 gonna로 들려요.','연음 익히기!','wanna는 want to예요.'),
    P('p_mi_wr_1','mi_write_basic','middle','middle2','sentence','영작 기초','normal','multiple_choice','빈칸에 들어갈 말은? “I like apples ___ they are sweet.”','because|but|or|if','because','이유는 because예요.','이유because!','but은 반대예요.'),
    P('p_mi_wr_2','mi_write_basic','middle','middle2','sentence','영작 기초','normal','multiple_choice','문장 뼈대 순서는?','S+V+O|S+O+V|V+S+O|O+S+V','S+V+O','영어는 주어+동사+목적어예요.','SVO!','한국어 어순이 아니에요.')
  ];
  window.GramProblemData = window.GramProblemData || [];
  window.GramProblemData = window.GramProblemData.concat(MI);
})();
