/* ============================================================
   문법아 놀자! - 정적 문제 데이터 (3/4: 고등 80개)
   - 가정법·준동사·관계사·당위성 심화 + GTELP 연결
   ============================================================ */
(function () {
  function P(id, cid, sl, gl, cat, un, lv, ty, q, ch, a, ex, hi, wr) {
    return { id: id, conceptId: cid, schoolLevel: sl, gradeLevel: gl, category: cat,
      unit: un, level: lv, type: ty, question: q,
      choices: ch ? ch.split('|') : null, answer: a,
      explanation: ex, hint: hi || '', wrongReason: wr || '' };
  }
  var HI = [
    P('p_hi_mix_1','hi_subj_mix','high','high1','subjunctive','가정법 심화','hard','multiple_choice','빈칸에 들어갈 말은? “If she had slept, she ___ fine now.”','would be|would have been|will be|is','would be','if 과거완료+지금 결과는 would+원형이에요.','시간 따로!','would have been은 과거 결과예요.'),
    P('p_hi_mix_2','hi_subj_mix','high','high1','subjunctive','가정법 심화','hard','multiple_choice','혼합 가정법 판단 기준은?','두 절 시간 다름|두 절 시간 같음|if절 미래|주절 현재','두 절 시간 다름','시간이 다르면 혼합 가정법이에요.','시간 비교!','같으면 일반 가정법이에요.'),
    P('p_hi_noun_1','hi_subj_noun','high','high1','subjunctive','가정법 심화','hard','multiple_choice','빈칸에 들어갈 말은? “It is time he ___.” (go, 과거)','went|go|goes|will go','went','It is time 뒤는 과거 went예요.','time+과거!','go 원형은 안 돼요.'),
    P('p_hi_noun_2','hi_subj_noun','high','high1','subjunctive','가정법 심화','hard','multiple_choice','“마치 ~인 것처럼”은? “as if he ___ sick.”','were|is|will be|are','were','as if 뒤는 과거 were예요.','as if+과거!','is는 안 돼요.'),
    P('p_hi_inv_1','hi_subj_inversion','high','high2','subjunctive','가정법 심화','hard','multiple_choice','빈칸에 들어갈 말은? “___ I rich, I would travel.”','Were|Was|Am|If was','Were','If 생략 도치는 Were+주어예요.','If 빼고 Were!','Was 도치는 안 돼요.'),
    P('p_hi_inv_2','hi_subj_inversion','high','high2','subjunctive','가정법 심화','hard','multiple_choice','“Had he left”는 무슨 뜻?','만약 그가 떠났다면|그는 떠났다|그는 떠날 것이다|그는 떠나고 있다','만약 그가 떠났다면','Had 도치는 가정법 과거완료예요.','Had=만약!','단순 과거가 아니에요.'),
    P('p_hi_seq_1','hi_tense_sequence','high','high1','tense','시제 심화','normal','multiple_choice','빈칸에 들어갈 말은? “He said he ___ busy.” (be, 과거)','was|is|will be|are','was','said(과거) 뒤는 was로 맞춰요.','주절 과거→was!','is 현재형은 안 돼요.'),
    P('p_hi_seq_2','hi_tense_sequence','high','high1','tense','시제 심화','normal','multiple_choice','“내일”을 간접화법으로? “tomorrow”→','the next day|yesterday|today|now','the next day','tomorrow는 the next day로 바꿔요.','시간도 바꾸기!','그대로 쓰면 안 돼요.'),
    P('p_hi_rep_1','hi_reported','high','high1','tense','시제 심화','normal','multiple_choice','빈칸에 들어갈 말은? “‘Close it.’→asked me ___ it.”','to close|close|closed|closing','to close','명령 간접은 to+원형이에요.','명령=to!','close 원형은 안 돼요.'),
    P('p_hi_rep_2','hi_reported','high','high1','tense','시제 심화','normal','multiple_choice','의문문 간접 접속사는? “Are you sick?”→asked ___ sick.','if|that|to|for','if','의문문은 if·whether로 전해요.','의문=if!','that은 평서예요.'),
    P('p_hi_quo_1','hi_quote_basic','high','high1','sentence','시제 심화','normal','multiple_choice','빈칸에 들어갈 말은? “She said she ___ ill.” (be, 과거)','was|is|will be|are','was','said 뒤는 was로 맞춰요.','said+was!','is는 안 돼요.'),
    P('p_hi_quo_2','hi_quote_basic','high','high1','sentence','시제 심화','normal','multiple_choice','간접 인용 접속사는? “said ___ she was sick”','that|if|to|for','that','평서는 that으로 전해요.','평서=that!','if는 의문예요.'),
    P('p_hi_rfst_1','hi_gerund_inf','high','high1','nonfinite','준동사 심화','hard','multiple_choice','그만둠 “담배를 끊었다”는? “I stopped ___.” (smoke)','smoking|to smoke|smoke|smokes','smoking','그만둠 stop은 ~ing예요.','stop+ing=그만둠!','to smoke는 멈추고 ~하기예요.'),
    P('p_hi_rfst_2','hi_gerund_inf','high','high1','nonfinite','준동사 심화','hard','multiple_choice','“잊었던 것을 기억하다”는? “remember ___”','~ing|to+원형|원형|과거','~ing','했던 것 기억은 ~ing예요.','했던 것=ing!','to는 할 것이예요.'),
    P('p_hi_nd_1','hi_need_dare','high','high2','nonfinite','준동사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “Let me ___ first.” (go)','go|to go|going|goes','go','let 뒤는 원형 go예요.','let+원형!','to go는 안 돼요.'),
    P('p_hi_nd_2','hi_need_dare','high','high2','nonfinite','준동사 심화','hard','multiple_choice','“need not” 뒤에는? “You need not ___.”','go|to go|going|goes','go','need not(조동사) 뒤 원형이에요.','need not+원형!','to go는 본동사 need예요.'),
    P('p_hi_perf_1','hi_part_perf','high','high2','nonfinite','준동사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “___ finished, he went out.”','Having|Have|Has|Had','Having','먼저 끝남은 Having+p.p.예요.','Having+완료!','Have 원형은 안 돼요.'),
    P('p_hi_perf_2','hi_part_perf','high','high2','nonfinite','준동사 심화','hard','multiple_choice','“먼저 온 것 같다”는? “seem ___ come early.”','to have|to having|have|having','to have','먼저 끝남은 to have+p.p.예요.','to have+완료!','to having은 없어요.'),
    P('p_hi_what_1','hi_relative_what','high','high1','relative','관계사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “___ you want is here.”','What|Which|Who|Where','What','선행사 없으면 what이에요.','선행사 없음=what!','Which는 선행사가 필요해요.'),
    P('p_hi_what_2','hi_relative_what','high','high1','relative','관계사 심화','hard','multiple_choice','최상급 뒤 관계사는? “the best movie ___ I saw”','that|who|where|when','that','최상급 뒤는 that을 써요.','최상급=that!','who는 사람예요.'),
    P('p_hi_prep_1','hi_relative_prep','high','high2','relative','관계사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “the room ___ I study” (in+which)','in which|in that|in where|in when','in which','전치사 뒤는 which! in which예요.','전치사+which!','that은 전치사 뒤에 못 와요.'),
    P('p_hi_prep_2','hi_relative_prep','high','high2','relative','관계사 심화','hard','multiple_choice','“누구든지 ~하는 사람”은?','whoever|who|whom|whose','whoever','일반화 anyone who는 whoever예요.','-ever=누구든지!','who는 특정 사람이에요.'),
    P('p_hi_while_1','hi_conn_sub','high','high1','connector','연결어 심화','normal','multiple_choice','빈칸에 들어갈 말은? “___ I was cooking, he came.”','While|When ever|If only|Because of','While','긴 동안은 While이에요.','동안While!','순간은 When이에요.'),
    P('p_hi_while_2','hi_conn_sub','high','high1','connector','연결어 심화','normal','multiple_choice','“~하자마자”는?','as soon as|as long as|as far as|as well as','as soon as','하자마자는 as soon as예요.','soon=곧!','as long as는 조건이에요.'),
    P('p_hi_how_1','hi_conj_adv','high','high1','connector','연결어 심화','normal','multiple_choice','빈칸에 들어갈 말은? “He was sick; ___, he came.” (그러나)','however|because|so|and','however','문장 사이 그러나는 however예요.',';=however!','because는 이유예요.'),
    P('p_hi_how_2','hi_conj_adv','high','high1','connector','연결어 심화','normal','multiple_choice','“그러므로”는?','therefore|however|moreover|otherwise','therefore','그러므로는 therefore예요.','결과=therefore!','however는 반대예요.'),
    P('p_hi_ine_1','hi_mand_adj','high','high2','mandative','당위성 심화','hard','multiple_choice','빈칸에 들어갈 말은? “It is essential that she ___.” (be)','be|is|was|being','be','당위 형용사 뒤 that절은 원형 be예요.','INE+원형!','is는 틀려요.'),
    P('p_hi_ine_2','hi_mand_adj','high','high2','mandative','당위성 심화','hard','multiple_choice','당위 요구 명사는?','demand|like|hobby|dream','demand','demand 뒤 that+원형이에요.','demand+원형!','like 뒤는 ~ing·to예요.'),
    P('p_hi_bet_1','hi_modal_idiom','high','high2','modal','조동사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “You had better ___ now.” (leave)','leave|to leave|leaving|leaves','leave','had better 뒤 원형이에요.','better+원형!','to leave는 안 돼요.'),
    P('p_hi_bet_2','hi_modal_idiom','high','high2','modal','조동사 심화','hard','multiple_choice','“~하기로 되어 있다”는?','be supposed to|had better|would rather|used to','be supposed to','예정·의무는 be supposed to예요.','supposed=예정!','had better는 충고예요.'),
    P('p_hi_being_1','hi_passive_adv','high','high2','voice','수동태 심화','hard','multiple_choice','빈칸에 들어갈 말은? “The road ___ repaired.” (have, 완료)','has been|is being|was being|is been','has been','완료 수동은 has been+p.p.예요.','완료=been!','is been은 없어요.'),
    P('p_hi_being_2','hi_passive_adv','high','high2','voice','수동태 심화','hard','multiple_choice','“고치는 중” 수동은? “___ fixed now”','is being|has been|was been|is been','is being','진행 수동은 is being+p.p.예요.','진행=being!','has been은 완료예요.'),
    P('p_hi_it_1','hi_emphasis','high','high3','sentence','문장 심화','hard','multiple_choice','빈칸에 들어갈 말은? “It was ___ that called.” (he)','he|him|his|himself','he','강조 It was+주격+that예요.','It~that+주격!','him 목적격은 안 돼요.'),
    P('p_hi_it_2','hi_emphasis','high','high3','sentence','문장 심화','hard','multiple_choice','Never 앞 도치 “한 번도 본 적 없어”는? “Never ___ I seen.”','have|has|had had|having','have','Never 앞 도치는 have+주어예요.','Never+have!','has는 3인칭이에요.'),
    P('p_hi_eli_1','hi_ellipsis','high','high3','sentence','문장 심화','hard','multiple_choice','빈칸에 들어갈 말은? “I like tea, and she ___.” (do)','does too|do too|does either|do either','does too','긍정 동의 대동사는 does too예요.','긍정too!','either는 부정이에요.'),
    P('p_hi_eli_2','hi_ellipsis','high','high3','sentence','문장 심화','hard','multiple_choice','앞 명사 대신 받는 말은? “I need a pen. Give me ___.”','one|it|that|this','one','막연한 하나는 one으로 받아요.','막연=one!','it은 특정이에요.'),
    P('p_hi_dep_1','hi_prep_verb','high','high1','pos','전치사·연어 심화','normal','multiple_choice','빈칸에 들어갈 말은? “arrive ___ Seoul”','in|at|to|for','in','큰 도시 앞에는 in이에요.','도시in!','to는 방향이에요.'),
    P('p_hi_dep_2','hi_prep_verb','high','high1','pos','전치사·연어 심화','normal','multiple_choice','“의존하다”는? “depend ___”','on|to|for|at','on','depend on이 짝꿍이에요.','depend on!','to는 안 돼요.'),
    P('p_hi_fond_1','hi_prep_noun','high','high2','pos','전치사·연어 심화','normal','multiple_choice','빈칸에 들어갈 말은? “in charge ___ sales”','of|for|to|at','of','in charge of가 짝꿍이에요.','of 짝꿍!','for는 안 돼요.'),
    P('p_hi_fond_2','hi_prep_noun','high','high2','pos','전치사·연어 심화','normal','multiple_choice','“~을 돌보다”는?','take care of|take care for|take care to|take care at','take care of','돌보다는 take care of예요.','통째로 외우기!','for는 안 돼요.'),
    P('p_hi_the_1','hi_compare_adv','high','high1','comparison','비교 심화','hard','multiple_choice','빈칸에 들어갈 말은? “___ higher, ___ better.”','The, the|A, a|More, more|Most, most','The, the','할수록 ~은 The+비교급 쌍이에요.','The 쌍둥이!','A는 안 돼요.'),
    P('p_hi_the_2','hi_compare_adv','high','high1','comparison','비교 심화','hard','multiple_choice','“~만큼 2배”는? “twice ___ big”','as|than|more|most','as','배수는 twice as~as예요.','twice as!','than은 비교급이에요.'),
    P('p_hi_er_1','hi_compare_double','high','high2','comparison','비교 심화','hard','multiple_choice','빈칸에 들어갈 말은? “Higher ___ higher.”','and|than|as|more','and','점점 강조는 -er and -er예요.','반복=점점!','than은 비교 대상이에요.'),
    P('p_hi_er_2','hi_compare_double','high','high2','comparison','비교 심화','hard','multiple_choice','“훨씬 더” 강조는?','much|many|little|few','much','비교급 강조는 much·far예요.','much 강조!','many는 개수예요.'),
    P('p_hi_love_1','hi_article_ab','high','high1','article','관사·명사 심화','hard','multiple_choice','일반 “사랑은 눈멀었다”는? “___ love is blind.”','(무관사)|the|a|an','(무관사)','일반 추상은 관사 없이 써요.','일반=×!','the는 특정이에요.'),
    P('p_hi_love_2','hi_article_ab','high','high1','article','관사·명사 심화','hard','multiple_choice','“그 사랑(특정)”은?','the love|a love|love|an love','the love','특정 추상은 the를 붙여요.','특정=the!','무관사는 일반이에요.'),
    P('p_hi_paper_1','hi_noun_count','high','high1','article','관사·명사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “two ___ of paper”','pieces|papers|paper|a paper','pieces','종이 장수는 pieces of예요.','단위 명사!','papers는 신문 여러 부예요.'),
    P('p_hi_paper_2','hi_noun_count','high','high1','article','관사·명사 심화','hard','multiple_choice','“조언 하나”는?','a piece of advice|an advice|advices|an advise','a piece of advice','셀 수 없는 advice는 piece로 세요.','piece로 세기!','advices는 없어요.'),
    P('p_hi_num_1','hi_quantifier','high','high2','article','관사·명사 심화','hard','multiple_choice','빈칸 동사는? “A number of birds ___.”','are|is|was|be','are','A number of+복수+복수동사예요.','A number=많은!','is 단수는 안 돼요.'),
    P('p_hi_num_2','hi_quantifier','high','high2','article','관사·명사 심화','hard','multiple_choice','“3분의 1”은?','one third|three one|one three|third one','one third','분수는 one third예요.','분자-분모!','three one은 없어요.'),
    P('p_hi_each_1','hi_pron_each','high','high2','pos','대명사 심화','hard','multiple_choice','빈칸에 들어갈 말은? “Each ___ ready.”','is|are|were|be','is','Each는 단수! is예요.','each+단수!','are는 안 돼요.'),
    P('p_hi_each_2','hi_pron_each','high','high2','pos','대명사 심화','hard','multiple_choice','“둘 다 아니다”는?','neither|either|each|every','neither','둘 다 아님은 neither예요.','neither=둘 다 아님!','either는 둘 중 하나예요.'),
    P('p_hi_one_1','hi_concord','high','high2','sentence','문장 심화','hard','multiple_choice','빈칸에 들어갈 말은? “One of them ___ absent.”','is|are|were|be','is','One of+복수+단수동사예요.','One=단수!','are는 안 돼요.'),
    P('p_hi_one_2','hi_concord','high','high2','sentence','문장 심화','hard','multiple_choice','“Ten miles”는 단수일까 복수일까?','단수|복수|둘 다|셀 수 없음','단수','거리·금액은 단수로 받아요.','거리=단수!','복수로 받으면 안 돼요.'),
    P('p_hi_they_1','hi_read_detail','high','high1','connector','독해 연결','normal','multiple_choice','they가 가리키는 것은? (지문 속 they)','앞 문장의 명사|뒤 문장|보기|제목','앞 문장의 명사','they는 앞 명사를 받아요.','앞 찾기!','뒤 문장이 아니에요.'),
    P('p_hi_they_2','hi_read_detail','high','high1','connector','독해 연결','normal','multiple_choice','however 뒤 내용은?','반대·전환|같은 말|예시|농담','반대·전환','however 뒤는 반대예요.','however=반대!','같은 말이 아니에요.'),
    P('p_hi_flow_1','hi_read_struct','high','high2','connector','독해 연결','normal','multiple_choice','글 첫 문장 역할은?','주장·주제|예시|농담|각주','주장·주제','첫 문장은 주장이에요.','첫=주장!','예시는 중간이에요.'),
    P('p_hi_flow_2','hi_read_struct','high','high2','connector','독해 연결','normal','multiple_choice','글 중간 문장 역할은?','근거·예시|주장|제목|날짜','근거·예시','중간은 근거·예시예요.','중간=근거!','주장은 첫 문장이에요.'),
    P('p_hi_how2_1','hi_write_cohesion','high','high2','connector','독해 연결','normal','multiple_choice','반대 내용을 이을 때는?','However|Moreover|First|Second','However','반대는 However예요.','반대However!','Moreover는 추가예요.'),
    P('p_hi_how2_2','hi_write_cohesion','high','high2','connector','독해 연결','normal','multiple_choice','내용을 추가할 때는?','Moreover|However|Although|But','Moreover','추가는 Moreover예요.','추가Moreover!','However는 반대예요.'),
    P('p_hi_sig_1','hi_listen_signal','high','high1','connector','청취 연결','normal','multiple_choice','들을 때 반전 신호어는?','but·however|and·or|first·second|one·two','but·however','but 뒤가 핵심이에요.','but 뒤 집중!','and 뒤는 나열이에요.'),
    P('p_hi_sig_2','hi_listen_signal','high','high1','connector','청취 연결','normal','multiple_choice','들을 때 이유 신호어는?','because|but|however|or','because','because 뒤가 이유예요.','because=이유!','but은 반대예요.'),
    P('p_hi_dict_1','hi_vocab_root','high','high1','pos','어휘 확장','normal','multiple_choice','transport의 port 뜻은?','나르다|말하다|보다|듣다','나르다','port는 나르다예요.','port=나르다!','dict가 말하다예요.'),
    P('p_hi_dict_2','hi_vocab_root','high','high1','pos','어휘 확장','normal','multiple_choice','dict(말하다)가 들어간 말은?','predict|transport|import|export','predict','pre+dict=미리 말하다예요.','dict=말!','transport는 port예요.'),
    P('p_hi_take_1','hi_vocab_colloc','high','high2','pos','어휘 확장','normal','multiple_choice','빈칸에 들어갈 말은? “take ___” (비행기가 뜨다)','off|on|in|at','off','take off는 뜨다예요.','통째로!','on은 켜다예요.'),
    P('p_hi_take_2','hi_vocab_colloc','high','high2','pos','어휘 확장','normal','multiple_choice','“돌보다” 구동사는?','look after|look at|look for|look up','look after','look after는 돌보다예요.','after=뒤치다꺼리!','look at은 보다예요.'),
    P('p_hi_lie_1','hi_confuse_lie','high','high1','subjunctive','헷갈림 정리','hard','multiple_choice','“책을 빌려주다”는?','lend|borrow|buy|bring','lend','빌려주다=lend, 빌리다=borrow예요.','주다lend!','borrow는 빌리다예요.'),
    P('p_hi_lie_2','hi_confuse_lie','high','high1','subjunctive','헷갈림 정리','hard','multiple_choice','“눕다” 과거는? “lie-lay-___”','lain|laid|lied|layed','lain','눕다lie 과거분사는 lain예요.','lie-lain!','laid는 놓다예요.'),
    P('p_hi_rise_1','hi_confuse_rise','high','high1','subjunctive','헷갈림 정리','hard','multiple_choice','“손을 들다”는?','raise|rise|sit|seat','raise','올리다(타동사)는 raise예요.','올리다raise!','rise는 오르다예요.'),
    P('p_hi_rise_2','hi_confuse_rise','high','high1','subjunctive','헷갈림 정리','hard','multiple_choice','“앉다”는? “sit-sat-___”','sat|sitted|sited|seat','sat','sit 과거는 sat예요.','sit-sat!','seat는 자리예요.'),
    P('p_hi_aff_1','hi_confuse_affect','high','high2','subjunctive','헷갈림 정리','hard','multiple_choice','“영향을 주다” 동사는?','affect|effect|effort|afford','affect','동사 영향을 주다=affect예요.','A동사!','effect는 명사 효과예요.'),
    P('p_hi_aff_2','hi_confuse_affect','high','high2','subjunctive','헷갈림 정리','hard','multiple_choice','바른 문장은? “return / return back”','return|return back|return again|revert back','return.','return back은 중복! return만 써요.','중복 빼기!','back·again 중복은 안 돼요.'),
    P('p_hi_spot_1','hi_error_spot','high','high3','subjunctive','헷갈림 정리','hard','multiple_choice','오류 찾기 1순위는? (밑줄 4곳)','시제|뜻|길이|철자 예쁨','시제','시제 오류가 가장 잦아요.','시제 먼저!','뜻만 보면 놓쳐요.'),
    P('p_hi_spot_2','hi_error_spot','high','high3','subjunctive','헷갈림 정리','hard','multiple_choice','오류 찾기 2순위는?','수 일치|글자 수|문장 길이|보기 번호','수 일치','주어·동사 수 일치를 봐요.','수 확인!','길이는 상관없어요.'),
    P('p_hi_map_1','gt_intro','high','high3','sentence','GTELP 입문','normal','multiple_choice','GTELP 문법에서 가장 많은 유형 2개는?','시제·가정법|조동사·관계사|연결어·당위성|준동사·조동사','시제·가정법','시제6+가정법6=12문항 절반이에요.','6-6 절반!','조동사는 2문항이에요.'),
    P('p_hi_map_2','gt_intro','high','high3','sentence','GTELP 입문','normal','multiple_choice','당위성은 몇 문제?','3문제|6문제|5문제|2문제','3문제','당위성은 3문항! 시제로 착각 주의예요.','당위3!','6문제는 시제예요.'),
    P('p_hi_time_1','gt_time_plan','high','high3','tense','GTELP 입문','normal','multiple_choice','문법 26문항 문항당 목표 시간은?','45초|2분|3분|5분','45초','20분÷26문항≈45초예요.','45초!','2분이면 시간이 모자라요.'),
    P('p_hi_time_2','gt_time_plan','high','high3','tense','GTELP 입문','normal','multiple_choice','막힌 문제는 어떻게?','표시하고 넘기기|3분 매달리기|찍고 끝내기|건너뛰고 안 돌아오기','표시하고 넘기기','모르면 표시→나중에 돌아와요.','넘기기 전략!','매달리면 뒤를 못 풀어요.'),
    P('p_hi_tech_1','hi_test_taking','high','high3','sentence','실전 전략','normal','multiple_choice','보기 4개 중 2개를 지우면 확률은?','50%|25%|75%|100%','50%','2개 남으면 50%예요.','소거=점수!','25%는 그대로 찍기예요.'),
    P('p_hi_tech_2','hi_test_taking','high','high3','sentence','실전 전략','normal','multiple_choice','막힌 문제 전략으로 맞는 것은?','표시하고 넘기기|처음부터 순서대로만|검토 안 하기|빈칸으로 두기','표시하고 넘기기','시간 확보가 먼저예요.','시간 먼저!','빈칸은 최악이에요.')
  ];
  window.GramProblemData = window.GramProblemData || [];
  window.GramProblemData = window.GramProblemData.concat(HI);
})();
